### ISSUE TITLE
Emergencies

### ISSUE THREAD

**Issue by voodoo070** [CorsixTH/CorsixTH#1032]
#### Describe the issue
When you do an emergency, the last patient always "dies" even if he does not (boo sound gets played)
If the emergency is 10 people, you will get 10 deaths added to your death count even if you cure them all

#### Steps to Reproduce
1. Start emergency

2. Cure everybody

3. Check death count

#### Expected Behavior

The actual number of deaths get added to the death count

#### System Information

CorsixTH Version: 0.60 beta 1

Operating System: Windows 7

**Comment by sadger** [comment]
Can confirm this seems to happen at least for one emergency I tried. Needs further investigation.

**Comment by voodoo070** [comment]
Makes it very hard to do some levels since you basically have to decline every single emergency
I only took the King Complex emergencies once i had a cure buffer since they pay out twice ;)

**Comment by sadger** [comment]
Really appreciate the bug finding, and sorry for any game problems its causing. Looks like we have a whole host of potentially related bugs at the moment but we already have some ideas to fix them! :smile:

**Comment by voodoo070** [comment]
well i loved the game as a kid and i do a playthrough every few years
was surprised with the bugs to be honest.. makes it quite difficult to get through the campaign :(
thanks for doing this high res open version tho :)
appreciate it a lot

**Comment by sadger** [comment]
You certainly must have played a lot to spot some of these bugs. We are always in need of testers too so if you want to help out please stick around, we'd really appreciate it. We are preparing for our new release which is why its extra important to squash these pesky things. Glad you enjoy it on the most part though :smile:

**Comment by voodoo070** [comment]
well i got a couple levels to do, i've run into a bunch of other bugs like the game crashing when rooms explode with people inside tho
i just dont know when it happens exactly and how to reproduce

**Comment by sadger** [comment]
Saves just before help if you get them, sometimes you get lucky with Autosaves. Then its easy for us to test as we can test the save before and after the fix. Don't stress too much about pinning it down, just reporting it with as much info as you can helps us out a lot.

**Comment by voodoo070** [comment]
yeah ill grab the save from before it happens and after
if i notice quickly enough for the autosave to still exist that is

**Comment by TheCycoONE** [comment]
This was left off with @voodoo070 saying he would get saves. Is that still something you're working on?

**Comment by antibones** [comment]
It is very easy to replicate - any emergency with more than one patient triggers this behaviour. I'll try and get a save to show this happening.

**Comment by antibones** [comment]
Here are some saves showing the bug (before and after) - accept the emergency displayed and wait for ever patient to be cured (sucessfully on mine) the final patient will be cured yet the death sound will play and the count will increment incorrectly

[1032 Save.zip](https://github.com/CorsixTH/CorsixTH/files/217941/1032.Save.zip)

This does not happen with only a single emergency patient

**Comment by Wowbagger2004** [comment]
Hi,  
Here's a video showing this bug and a savegame from just before it was recorded.

You can see that my hospital copes with the emergency but it counts the last patient as having been killed, even though he was actually cured.

https://youtu.be/UlBWYjNPPUM

[emergency.zip](https://github.com/CorsixTH/CorsixTH/files/219722/emergency.zip)

Thanks very much!  And thanks in general for this excellent project!

**Comment by TheCycoONE** [comment]
Looks to be fixed now, probably by #1034

**Comment by TheCycoONE** [comment]
Sorry, I misunderstood the issue. Will continue to investigate.

**Comment by immaculation** [comment]
Hi - might be able to shed some small light on this...what I've observed running 0.50

X = total death toll
= Sum of each disease death toll

Emergency for any given disease, where the death toll for that disease is n, at the end of the emergency it seems to always be n+1 irrespective of if anyone dies. Announcer announces the new death toll as X +1. When you look at the casebook for the disease, the death toll for that disease is NOT n+1 but n + (X+1) ie n + the new grand total. Only seen this bug where n = 0, so it either increments that disease death toll by (X+1) or replaces it by (X+1).

The Grand total equation ie sum of each disease death total is maintained and thus at the end of this chain of events, is equal to 

X1 = X + (X+1)

(instead of X1 = X + 1), again, notwithstanding that no one may have died as part of the emergency.

**Comment by TheCycoONE** [comment]
This has been fixed in master.
