### ISSUE TITLE
Music keeps playing when game is out of focus.

### ISSUE THREAD

**Issue by sherief** [CorsixTH/CorsixTH#1053]
Exactly what it says on the can.
#### Steps to Reproduce

Start a new game.
Alt+Tab away from the game.
#### Expected Behavior

Either mute the audio unconditionally, or make it an option. Muting audio seems to be a sensible default.
#### System Information

**CorsixTH Version: 0.60 beta-2

**Operating System: Windows 10

**Theme Hospital Version: GOG.com

**Comment by TheCycoONE** [comment]
Sounds reasonable to me. At this point it's too late to land in 0.60, but I suspect it could be fairly easily implemented for the next version.

**Comment by antibones** [comment]
Could it be an option instead of unconditional. I play on multiple monitors so naturally the game loses focus a lot and this would be very distracting.

**Comment by TheCycoONE** [comment]
It could be. Is there any precedent for this feature?

**Comment by TheCycoONE** [comment]
I did a quick google search and find a lot of people on both sides of the option for numerous mainstream games. An option seems like the best way to please everyone.

**Comment by sherief** [comment]
I strongly advocate for a heuristic. In the case where the game is running full-screen, and the machine has one screen attached, music should stop on focus loss. This should change on multimon systems based on @antibones's comment, since in his case it makes sense for it *not* to stop playing music or pause on focus loss.

**Comment by TheCycoONE** [comment]
My opinion is that such a heuristic complicates the matter and still runs the risk of not pleasing everyone.

**Comment by sherief** [comment]
Why? It's actually simpler than it sounds - you can just check whether your window is occluded or not. If it's occluded, mute music; if it's visible play music. Then add an override for this.

**Comment by TheCycoONE** [comment]
And how do we know if the window is occluded (partially or fully)? What happens when the user moves the window covering the game window without focusing on the game? How can we tell?

If you know how to do these things, volunteer to write the patch. If you don't, please avoid insinuating that it's simple.

**Comment by sherief** [comment]
Dude, chillax, nothing is worth getting this riled about. I haven't looked at the code, but SDL 2 has window events that inform the app about window visibility and focus: https://wiki.libsdl.org/SDL_WindowEvent

If that doesn't work, I can offer a patch to SDL 2. If that still won't work, I can hook up something up internally using DXGI's DXGI_STATUS_OCCLUDED for Windows and NSWindowOcclusionState for OS X.

If the above pointers are insufficient, feel free to point me towards the code, but I currently have a good chunk of GPU code on my plate and it'll take me a while to ramp up with this code base.

**Comment by antibones** [comment]
Just my opinions, I've been weighing up a heuristic or an option and I still think a simple toggle option is the way to go. 
Firstly as TheCycoONE has pointed out such a patch would introduce a lot of technical debt and edge cases. Regardless of the technical difficulty such a patch would be significantly more complex than a simple toggle option. Even if sherief supplies or helps develop such a feature who will support it going forwards, I foresee it being removed if the developers do not fully understand the code and sherief is not available. 

Secondly I think forcing certain behaviours on the user is bad, what if today I don't want the music whilst the window is out of focus on a multiple monitor system. What happens if a person with a single monitor wants to hear the game in the background. The developers would have to anticipate and force a decision on the users whereas a toggle can follow the original games behaviour as default.

Finally for users with laptops the behaviour would be inconsistent. If you have another monitor attached whilst playing the game you will be used to the game playing music in the background. The average user would still expect the game to do that without a monitor attached. The correlation between game audio whilst the window is out of focus and whether your laptop is plugged into a monitor is non obvious and I foresee some confusion if we make this option automatic.

**Comment by TheCycoONE** [comment]
@sherief Sorry, I had Real Life (tm) reasons for being more tense than usual yesterday. If I end up being the one to implement this feature I'll play with all options that can be accomplished with SDL window events. I would definitely include a toggle in the config as well because no behavior is going to please everyone. I'm sure some people would also want the game to auto pause and others would not.

**Comment by sherief** [comment]
Okay, valid concerns so far. Let me try to come up with a proposal considering all the points raised.

Let's consider the following rule as the default option for music management:

"Any time the game window is fully occluded, mute the music."

Of course, there should be an option exposed to the user controlling this, but for now I'm considering the default.

There are two cases to cover: single monitor and multi monitor.

In the single monitor case, I don't see an issue: if the player is in windowed mode it won't kick in unless they switch desktops, and if they're in fullscreen mode it won't kick in unless they switch to another process. Am I missing any cases here?

In the multi monitor case: If the user has the game partially or wholly visible on any monitor, this rule will keep the music playing, so you can get your TH on while browsing 9GAG or Twitter. Only when all screens have non-TH windows will this kick in, in which case I can't see it as an issue. 

Again, this is my suggestion for the defaults - I totally agree that a toggle should be exposed to the user.

What problems can you spot in this proposal?

**Comment by Alberth289346** [comment]
At my Linux system, I don't get all those SDL events. Losing and gaining focus works, but is generally useless, since I use "focus follows mouse", so whenever I move the mouse out of the window, you get those (like type a line of chat in a window at the same desktop).
Otherwise, the minimize and restore seems to work, with "hidden" and "exposed", and the moved to position stuff. In particular, you don't get anything when you don't have focus (ie move the mouse out of the window, for me), so switching to a different desktop, dragging another window on top of it, etc is not reported at all.

**Comment by sherief** [comment]
FWIW, my proposal doesn't look at focus at all:

"Any time the game window is fully occluded, mute the music."

only occlusion. But it seems SDL2 doesn't handle occlusion properly and honestly, like you said, there's a zillion different window managers out there. What do people think as for ideas to make things work for OS X / Windows users while not giving Linux users the short end of the stick?

**Comment by Alberth289346** [comment]
From my experiments, it seems the following options exist for Linux

1. Always on
2. On if on screen somewhere (== not minimized)
3. On if focus
4. Always off

I think this is more or less in order of "less music".

Option 3 is useless to me due to my focus model, but if you use "click to give focus", it would work. Assuming you can't have focus when occluded, your option would be tween 2 and 3, I think?

**Comment by sherief** [comment]
2 seems to make the most sense to me - you?

**Comment by Alberth289346** [comment]
I think as user you want to be able to specify at least 1 and 4. Option 2 sounds reasonable too, so that would be useful to have too. I don't know about 3, I can imagine it's a useful choice when you have click-to-focus models, like in Windows. I won't use it though.

 If you want to add occlusion magic, make it an extra option, imho.

**Comment by sherief** [comment]
Yes, of course as a user you'll be given a option to force 1 and 4 - I'm talking about the default in this case. I also don't want this to spiral into an over-complex monster. I think ultimately the options for audio should be:

- Always on
- Always off
- On while visible

I think separating things into three options for every sound type is just added complexity.

**Comment by Alberth289346** [comment]
we already have 3 options, look in the menu, but otherwise, sounds good to me

**Comment by lewri** [comment]
Merging into #2370 as this deals with a wider scope than just music.
