### ISSUE TITLE
Handymen trying to water plant blocks room

### ISSUE THREAD

**Issue by jorritb** [CorsixTH/CorsixTH#1081]
#### Describe the issue

I noticed that there are two handymen waiting outside my Jelly Vat who seem to want to go in and water the plant, but they never go in and block the room. When I pick one up and place him in the room he just stands in the room waiting (he stands exactly behind the Jelly Vat). When I pick up the handymen either inside or outside the room, more show up and also start waiting. If I fire all handymen, including the ones inside the room, they become stuck and the room remains unusable. The same happens if I try to delete the room.

![handymen-plant](https://cloud.githubusercontent.com/assets/11193663/15691761/ebfaaad4-278a-11e6-9b09-d04e521554df.png)
.
#### Steps to Reproduce

Check the save I attached (you probably also need the .map and .level since this is a custom map)

Save file: https://drive.google.com/open?id=0B1z_KXLTgDplMzhWSlpONGdoTDQ
Level: https://drive.google.com/open?id=0B1z_KXLTgDplUmxab3R1MEw2dFE
Map: https://drive.google.com/open?id=0B1z_KXLTgDplcm5vMnpKQ3ZkQ1k
#### Expected Behavior

This shouldn't happen.
#### System Information

CorsixTH 0.60 om Windows 10.
#### Gamelog.txt

It only says "savegame version 111"

**Comment by TheCycoONE** [comment]
All these stuck room issues are very tricky. Thanks for the report.

**Comment by mugmuggy** [comment]
Here the door is reserved by the patient that I assume just used the door. They show up as having left the hospital and checking the previous_action (on trunk), the last action appears to be leaving the map (walking to the edge of the map), but they still have the door reserved.

The hack I guess it to update the hack in Door:checkForDeadlock to account for despawn actions
`      if action.name == "queue" or action.name == "spawn" and action.mode == "despawn" then`

**Comment by mugmuggy** [comment]
From some experimentation this bit of code appears to be contributing to the patients and potentially staff reserving the door.

https://github.com/CorsixTH/CorsixTH/blob/e14d4ffa993a1d3fa71b6bca293d77602f388c74/CorsixTH/Lua/humanoid_actions/walk.lua#L427-L429

I put an 

> if action.is_leaving then

check in place wrapping the assignment of the humanoid to the reserved_for and so far it seems fairly reliable in preventing the patient holding the door.

As the QueueAction and the Walk action both have reservations set.

https://github.com/CorsixTH/CorsixTH/blob/e14d4ffa993a1d3fa71b6bca293d77602f388c74/CorsixTH/Lua/humanoid_actions/walk.lua#L310-L313

The door is reserved when a patient leaves the queue, and I assume that the walk action after the queue action from above is reserving it again. Not to say this will fix it, just that I haven't happened upon it since I put that change in and a tweak elsewhere will probably be better.

**Comment by mugmuggy** [comment]
When staff are stuck and get tired in a room, they start a loop of trying to use the door, walk, idle queue, walk. But when that occurs the walk reserve_on_resume is actually droppped, as by this time, the Staff has ticked again, calling Staff:goToStaffRoom which upon doing so creates a new leave action I assume and we rinse and repeat.

As the reservation is then lost on the walk action the door doesn't get reserved on that walk action resumption. I assume then there is still a race of another humanoid reserving the door, ie the patient leaving, but the staff can't as the walk has been removed by this point. Putting a guard to just not do the guts of goToStaffRoom again as just an example;
```lua
  if self.going_to_staffroom then
    return
  end
```
Will stop the walk loop and the staff member stands idle in the queue. Then it should just be a matter of finding why the reservation of the other leaving humanoid isn't lifted. Instead of the blunt check from previous comment.

**Comment by mugmuggy** [comment]
I've come across a few, and some of the other door reservations may follow this state but in a game that has lots of epidemics, it seems to come up more often due to the forced kick.

The Issue 1394 has a couple of stuck doors where one (cardio), I wait until a patient queues, then do these steps to manipulate the game state to replicate what appears to happen spontaneously.

1. Alter the waiting patients thirst attribute above the threshold.
2. Move the stuck staff member out and place another in there 
3. Remove the door.reserved_for and then redrop the staff member in the room to start advancing the queue.
4. Patient should then start to enter, as soon as the walk action starts, I pause and then run patient:tickDay() manually, Might have to run it a few times as there is a random check in the drinks machine logic.
5. Once the drink machine actions are queued, patient should abort the walk, and make way to drinks machine. The door stays reserved at this point.
6. Run patient:goHome("evacuated") on the patient, they leave the hospital, keeping the reservation set OR adjust patients toilet_need to above threshold.
7.  If adjusting toilet need, patient:tickDay until toilet seek occurs - this one you need random instances to fall in your favour, so logic might want to be altered in favour of seeking toilet instead of peeing in the corridor.
8. patient then goes to toilet and performs another SeekRoomAction potentially not returning to the same room they left from. - patient still has the old reservation.

The relevant check that needs a check for is_entering
https://github.com/CorsixTH/CorsixTH/blob/7dedff4bb094d750d86ed5c206deebbe0320f63e/CorsixTH/Lua/entities/humanoids/patient.lua#L830-L833

and here we have current.keep_reserved set
https://github.com/CorsixTH/CorsixTH/blob/7dedff4bb094d750d86ed5c206deebbe0320f63e/CorsixTH/Lua/entities/humanoids/patient.lua#L874-L878

Which leads to the reservation staying kept when the walk into the room is interrupted
https://github.com/CorsixTH/CorsixTH/blob/7dedff4bb094d750d86ed5c206deebbe0320f63e/CorsixTH/Lua/humanoid_actions/walk.lua#L75-L89

**Comment by mugmuggy** [comment]
I made a change and tested it fairly successfully
```lua
    if not self:getRoom() and not self:getCurrentAction().is_leaving and not self.going_home and
        not (self:getCurrentAction().is_entering and self:getCurrentAction().reserve_on_resume) then
```
That change in theory would allow a patient walking to a room, to stop by the drinks machine - as Room:createEnterAction walk will be is_entering, but the action won't have a reserve_on_resume as they need to join the queue first.

Likewise patients currently must not have an is_entering action either for using the toilets, so once they start walking they must get to the destination room and essentially queue before making way to the toilets. Vomit actions are the same as toilet (in Patient:tickDay()).

I don't know if the original allowed toilet use on walking to a room, or vomiting on the way to a room, but if it did the same check could be replicated there to include if the door was reserved. I'll try and confirm this.

**Comment by mugmuggy** [comment]
I confirmed the original with drinks machine - built a really hot hospital with corridors made of radiators, turned the heat up and placed a drinks machine - and patients don't appear to use the drinks machine unless queued and waiting for the room. Its a little bit trickier with the original as they don't need to get to the door to queue, but just close enough to the end of the queue, so maybe the is_entering check is enough (nearly).

Putting the same check on the toilet use, actually leads to the possibility of peeing within the toilets rather than vetoing that and just using the toilet so is_entering is probably enough for most cases, but the reserve_on_resume check appears to match mostly with what is currently occuring and preventing the interrupted walk leading to the reservation bug.

The main causes are drinks machine and epidemic evacuation or drinks machine leading to toilet seek resulting in walk to different room.
