### ISSUE TITLE
Mac OS X build

### ISSUE THREAD

**Issue by maki-chan** [CorsixTH/CorsixTH#1121]
Dear CorsixTH developers,

I did not know a better way to contact you, so I'll do it this way. I made an OS X build for v0.60 on Mountain Lion (10.8) and packed it as a nice DMG.

Unfortunately, it's not possible for me to check if it runs on other OS X systems, but I wanted to share it with you anyway, so it could be included in the v0.60 release tag as a download for others that aren't that tech-savvy to build their own CorsixTH on Mac.

The link to the download is [here](https://www.dropbox.com/s/460ousxcntp0wyq/CorsixTH_0.60.dmg?dl=0).

Best,
Michael

**Comment by TheCycoONE** [comment]
Wonderful, thanks maki-chan. I don't personally have OSX but I will but out a call for testers.

**Comment by TheCycoONE** [comment]
I extracted they dmg and I didn't see the dylib files. Possible I just missed them. Can you verify?

**Comment by bendyson** [comment]
Brilliant, thanks for this! Just tried this and it's crashing instantly for me.

Following on from what @TheCycoONE said, it does appear that the dylib files aren't included. 

**Here's the exact error message:**
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Applications/CorsixTH.app/Contents/MacOS/CorsixTH
  Reason: image not found

Binary Images:
    0x7fff61c08000 -     0x7fff61c3f007  dyld (360.19) <9D05FDF4-65CE-3B53-86D4-ABE1A5BF35F3> /usr/lib/dyld

**Comment by TheCycoONE** [comment]
@maki-chan Look at Tobylane's patches here: https://github.com/CorsixTH/CorsixTH/pull/1016 they may help with bundling the dylibs.

**Comment by maki-chan** [comment]
@TheCycoONE Thank you very much, will try the patches from #1016 tomorrow as soon as I get up (already late here) and will upload again as soon as possible.

I have OSX natively and additionally as a VM set up only for future CorsixTH development (the latter one has OSX 10.8 for compatibility reasons on builds), so I hope I can help developing for OSX.

**Comment by maki-chan** [comment]
I pulled #1016 over the b6fc9f9e0c6893720200088d21da4e2e14f0d319 commit (which is v0.60) and built it again with the `dist` target (additionally to the `CorsixTH` target) and that copied over the necessary dylibs (hopefully all of them).

@bendyson Could you have a look at it again? The link is the same, [this one](https://www.dropbox.com/s/460ousxcntp0wyq/CorsixTH_0.60.dmg?dl=0).

**Comment by TheCycoONE** [comment]
I don't see the library files for lfs, and mime/core and socket/core. I would have expected them to be either in the top level or under luarocks/lib/5.3?

**Comment by maki-chan** [comment]
They are in the `Contents/MacOS/luarocks/share/lua/5.3` subfolder of the application (and that should be exactly where they have to bee, as libraries and scripts are searched for in the `Contents/MacOS` folder.

**Comment by TheCycoONE** [comment]
When you built lpeg, lfs, and lua sockets you must have generated some sort of .so or .dylib file somewhere. Typically that's in ```luarocks/lib/5.3``` if you are using luarocks. These modules are composed of C code - that code cannot be translated to pure lua.

Do you have nothing in the above folder in your luarocks tree?

**Comment by maki-chan** [comment]
You are right, totally forgot about the C extensions behind those Lua packages.

I already mentioned it in the pull request #1016 
It seems that the `osx_luarocks` script had no copy commands for those libraries. After the additional commands I mentioned there, the libraries are now copied and I hope that now we have everything in the OSX .app bundle.

@bendyson Sorry to mention you again, but if you tried the last upload, you should try it now again. Sorry for the inconvenience. The link has not changed once again, and is still [here](https://www.dropbox.com/s/460ousxcntp0wyq/CorsixTH_0.60.dmg?dl=0).

**Comment by tobylane** [comment]
Your latest link works for me. The problem I'm stuck on is building the dylibs for an older architecture than I am currently on, e.g. core2 rather than native. Sorry, I don't appear to have documented this before now.

**Comment by joewestcott** [comment]
Latest link works great for me, it's nice to have all the v0.60 features!

**Comment by maki-chan** [comment]
@joewestcott Great to hear :)

@tobylane What do you mean with building for an older architecture? It's not possible for you to compile for 10.8 because you are on 10.9 or higher, or what do you mean exactly?

**Comment by tobylane** [comment]
Each set of Intel CPU releases (yearly?) is an architecture within x86_64. Xcode lets you pick between native, x64 and x86+x64, but I couldn't work out the non Xcode way (make -march) for lua/etc.

I built 0.60 with Lua 5.1 on my old iMac, with OS X 10.7.5 and Core 2 Duo (E8135) cpu. I include dylibs and luarocks for all lua versions and the CorsixTH.lua change from 1016. Please try this [Archive.zip.](https://github.com/CorsixTH/CorsixTH/files/452510/Archive.zip)

**Comment by TheCycoONE** [comment]
@tobylane did you miss luarocks/share? I don't see the lua files for the modules.

**Comment by tobylane** [comment]
Yes, I believe they aren't required, I can't find any difference when they are or aren't included. Here's just the app with the luarocks/share from /usr/local/share/lua/5.1 for testing this theory - [CorsixTH.zip](https://github.com/CorsixTH/CorsixTH/files/452629/CorsixTH.zip)

**Comment by TheCycoONE** [comment]
The lua socket ones are used for the upgrade check if available. It's possible the lpeg ones are not used but that shouldn't be relied on.

**Comment by tomyun** [comment]
Not sure how much it could add to this conversation, but just wanted to notify that Homebrew recently got a formula for CorsixTH: Homebrew/homebrew-games#645

You can install the latest version (0.60) by typing `brew install homebrew/games/corsixth`. Hope this help out some users building/running CorsixTH on Mac.

**Comment by TheCycoONE** [comment]
Excellent news, thanks @tomyun 

I'll edit the release page to mention both this ticket and the homebrew formula.

**Comment by jrussek** [comment]
Hey there,
both corsix installed via brew or really any of the files in this thread crash for me shortly after starting up (when it starts loading the game). The report says:

`Dyld Error Message:
  Symbol not found: _sws_getCachedContext
  Referenced from: /Users/USER/Downloads/CorsixTH.app/Contents/MacOS/CorsixTH
  Expected in: /Users/USER/Downloads/CorsixTH.app/Contents/MacOS/libswscale.dylib`

**Comment by tobylane** [comment]
Try `brew ffmpeg` and copy that dylib from /usr/local/Cellar/ffmpeg/3.0.1/lib (number may vary) into the Contents folder to see if a locally made version fixes this.

**Comment by jehoyes** [comment]
I used to be able to run the mac version on my OSX 10.6.8 Snow Leopard. It's stopped working and none of the files I've downloaded from this thread will run. 

I have a version: 0.11 that will run but has a non-functioning staff appointment panel. I'm very lost as to much of what has been said here, particularly when it came to the homebrew formula link. Not sure what I should do with that information. 

Don't think this thread is aimed at people like me who generally like to plug and play. I'm happy to tinker with package contents and system files if I'm given clear instructions. I'd love to get my themeHOSPITAL up and running again. I have the original PC disc.

**Comment by jehoyes** [comment]
Scratch that. I've now found a version that works. Thanks.

**Comment by TheCycoONE** [comment]
@jehoyes if the version you found is 0.50 or later, it would be worth pointing it out here.

**Comment by jehoyes** [comment]
It's version 0.11 

I was being dim about the staff appointments panel and was looking at the wrong dialogue box so, as far as I can see so far, everything is working fine as usual.

OSX 10.6.8 Snow Leopard running on a 2.66 GHz Intel Core 2 Duo iMac.

**Comment by rreina** [comment]
> @tomyun 
> Not sure how much it could add to this conversation, but just wanted to notify that Homebrew recently got a formula for CorsixTH: Homebrew/homebrew-games#645

Using this Homebrew formula worked for me in macOS Sierra 10.12.2. Thanks!

I had to do the following to compile CorsixTH:
1. Update brew:
`brew update`
2. Install required dependencies:
`brew install lua`
`sudo luarocks install lpeg`
`sudo luarocks install luafilesystem`
3. Execute the brew install command:
`brew install homebrew/games/corsixth`

**Comment by gakera** [comment]
The instructions in this thread and in the release notes as well (https://github.com/CorsixTH/CorsixTH/releases/tag/v0.60) seem to be depricated, when I do
`brew install homebrew/games/corsixth `
I get: `Warning: Use corsixth instead of deprecated homebrew/games/corsixth`

**Comment by TheCycoONE** [comment]
Updated release note text. Thanks @gakera

**Comment by JohnnyWalkerDesign** [comment]
Hi, I'm running 10.12.5 and when I finally point to the game directory (which took a while because it the file window kept not responding) I got this error message:

`Error loading languages/brazilian_portuguese.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/brazilian_portuguese.lua: Too many open files
Error loading languages/czech.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/czech.lua: Too many open files
Error loading languages/danish.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/danish.lua: Too many open files
Error loading languages/developer.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/developer.lua: Too many open files
Error loading languages/dutch.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/dutch.lua: Too many open files
Error loading languages/english.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/english.lua: Too many open files
Error loading languages/finnish.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/finnish.lua: Too many open files
Error loading languages/french.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/french.lua: Too many open files
Error loading languages/german.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/german.lua: Too many open files
Error loading languages/hungarian.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/hungarian.lua: Too many open files
Error loading languages/iberic_portuguese.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/iberic_portuguese.lua: Too many open files
Error loading languages/italian.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/italian.lua: Too many open files
Error loading languages/korean.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/korean.lua: Too many open files
Error loading languages/norwegian.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/norwegian.lua: Too many open files
Error loading languages/original_strings.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/original_strings.lua: Too many open files
Error loading languages/polish.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/polish.lua: Too many open files
Error loading languages/russian.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/russian.lua: Too many open files
Error loading languages/simplified_chinese.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/simplified_chinese.lua: Too many open files
Error loading languages/spanish.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/spanish.lua: Too many open files
Error loading languages/swedish.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/swedish.lua: Too many open files
Error loading languages/traditional_chinese.lua:
/usr/local/Cellar/corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/languages/traditional_chinese.lua: Too many open files
Language 'english' could not be found. Reverting to English.
An error has occurred in CorsixTH:
...sixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/strings.lua:305: Language 'English' could not be found. Please verify your installation.
stack traceback:
	[C]: in function 'error'
	...sixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/strings.lua:305: in function '_loadPrivate'
	...sixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/strings.lua:279: in function 'load'
	.../corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:407: in function 'initLanguage'
	.../corsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:229: in function 'init'
	...corsixth/0.60_1/CorsixTH.app/Contents/MacOS/CorsixTH.lua:133: in main chunk
	[C]: in ?
...orsixth/0.60_1/CorsixTH.app/Contents/MacOS/Lua/audio.lua:674: attempt to index field 'ui' (a nil value)
`

Hope it helps!

**Comment by tobylane** [comment]
@JohnnyWalkerDesign That is an unrelated error, I've had it in other programs. Just trying it again fixes it for me.

**Comment by JohnnyWalkerDesign** [comment]
Yes, you're right, it did.

**Comment by colinjmatt** [comment]
What's needed to resolve lfs/lpeg missing on build so that I can distribute a MacOS build? For now, I can manually copy lfs.so and lpeg.so from /usr/local/lib/lua/5.3/ to /Applications/CorsixTH.app/Contents/Resources/ and the build will then work correctly on my other Mac without any initial errors.

My coding abilities aren't the greatest, but I'm more than happy to try and help anywhere I can.

**Comment by colinjmatt** [comment]
For anyone that would like to try my build out, I've put my build of 0.62 [here](https://www.dropbox.com/s/nf66s7ihempp5si/CorsixTH%200.62.dmg?dl=0).

**Comment by TheCycoONE** [comment]
Manually copying lfs.so and lpeg.so is fine as long as they were built with the same link options.

How did you get your other dependencies?

**Comment by colinjmatt** [comment]
Everything has been built manually from source at the command line. The machine I'm using does not have Mac Ports / Homebrew installed.

**Comment by TheCycoONE** [comment]
Should be good then. What OS version did you target?

**Comment by colinjmatt** [comment]
Right now, I've built for 10.13.6 (latest MacOS build) but if this initial build is good and there's need for me to change the min version to something lower then I can happily do that.

**Comment by colinjmatt** [comment]
WHat I've compiled doesn't seem to function outside of /Applications. I presume this is something relatively simple that I haven't acocunted for?

**Comment by TheCycoONE** [comment]
It's not particularly simple, I wasn't able to come up with a workaround. It comes down to a couple lines in the CMakeLists.txt:
definitely: https://github.com/CorsixTH/CorsixTH/blob/b8e9d7ff500f357b8e7a6562e4aaec22c48ee102/CorsixTH/CMakeLists.txt#L25
and possibly: https://github.com/CorsixTH/CorsixTH/blob/b8e9d7ff500f357b8e7a6562e4aaec22c48ee102/CorsixTH/CMakeLists.txt#L252

The executable needs to know where to find the resource files in the app. Currently it does this by absolute path, defined at compile time. On windows it uses a relative path because the whole application lives in one directory and the working directory becomes that directory; on Linux it uses absolute paths because the application is installed by a distribution according to the FHS.

On MacOS I ran into complications. If I recall correctly, I found that the working directory wasn't fixed. The only good solution was to write a bunch of apple specific code like: https://stackoverflow.com/questions/516200/relative-paths-not-working-in-xcode-c

I polled our resident mac os using developers at the time and we decided it would be fine to leave it hard coded as long as we shipped an 'installer' to copy the app to Applications (like so many you must have seen).

So that's basically it - optimally the app would work anywhere and we'd have an installer; currently, 0.62 has to be run from a fixed location, so it's probably best to make an installer and maybe warn people up front.

**Comment by colinjmatt** [comment]
I'll research relative file paths to see if this is anything I can do. Perhaps not as simple as I once thought.

**Comment by TheCycoONE** [comment]
No, sorry my knowledge of MacOS is limited; but assuming your dmg opens one of those 'Drag to Applications' dialogs or the equivalent; that's awesome.

**Comment by colinjmatt** [comment]
That's exactly what it does - I've even gone so far as to add an icon and background much like the previous Mac packager did.

**Comment by TheCycoONE** [comment]
Alright, GitHub was flaking out uploading the dmg, so I've copied your dropbox link in the release announcement for now.

From personal experience, you could get a substantial size (and compile time) reduction by setting your ffmpeg flags like I do in vcpkg:
https://github.com/CorsixTH/vcpkg/blob/corsixth/ports/ffmpeg/portfile.cmake#L39
(Incorporate if you want, 30mb isn't going to make or break most people these days). Curious what you find about the paths, even if it ends up needing to go into 0.63.

**Comment by colinjmatt** [comment]
You mean the flags set when ffmpeg is compiled? I can indeed disable everything and give it a try.

**Comment by TheCycoONE** [comment]
Sorry, all the flags from lines 39 to 43, or else you won't be able to do much with it at all :)

**Comment by colinjmatt** [comment]
Ah! That makes more sense now. I'll give that a try shortly, just trying to resolve an issue with wxWidgets and AnimView so I can get that built and included too.

**Comment by TheCycoONE** [comment]
I don't ship AnimView with the other builds, since it's mostly a developer tool.

**Comment by colinjmatt** [comment]
I've managed to build it, so if anyone wants/needs it on MacOS I can supply it if needed. For now I'll leave it out.

**Comment by colinjmatt** [comment]
6mb .dmg file [here] (https://www.dropbox.com/s/2y08a1ndassst3h/CorsixTH%200.62.dmg?dl=0) :D

**Comment by Thorworx** [comment]
Any chance of getting a .dmg that will mount on El Cap?

> The following disk images couldn't be opened
> 
> CorsixTH.0.62.dmg
> Reason: no mountable file systems

**Comment by colinjmatt** [comment]
This looks to be a compatibility issue where .dmg images created on High Sierra as APFS are not compatible with El Capitain that uses HFS+.

Let me look into creating a .dmg with HFS+ support - it hopefully shouldn't take too much to force High Sierra to create that.

**Comment by Thorworx** [comment]
> Let me look into creating a .dmg with HFS+ support - it hopefully shouldn't take too much to force High Sierra to create that.
Thanx Colin, much appreciated.
Worse case scenario, can the .app just be zipped up for downloading? It seems like the APFS .dmg thing would be a serious artificial minimum system requirement.

**Comment by colinjmatt** [comment]
Please can you try [this one](https://drive.google.com/file/d/1-jjel7RQRF3_j33aINenEjv768VJCZaS/view?usp=sharing)?

**Comment by Thorworx** [comment]
> Please can you try this one?

Launching via GUI:
"Requires 10.13 or newer."

However, I was able to launch from within the app using terminal.

I got the CorsixTH GUI setup window, but was not able to select my Theme Hospital.app (GoG version) in the selector screen. Highlighting it and clicking okay does nothing. No error.. just nothing.

So I tried moving the resources out of original Theme Hospital.app figuring I'd be able to select that folder, but then I got a lot of errors: Error while fetching children for /Applications/... "too many open files"
... then:

```
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:897: attempt to index a nil value (local 'fi')
stack traceback:
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:897: in method 'saveConfig'
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1395: in method 'exit'
	.../Resources//Lua/dialogs/resizables/directory_browser.lua:188: in local 'callback'
	...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:682: in method 'handleClick'
	...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:1478: in method 'onMouseUp'
	...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:1462: in field 'onMouseUp'
	/Applications/CorsixTH.app/Contents/Resources//Lua/ui.lua:654: in function </Applications/CorsixTH.app/Contents/Resources//Lua/ui.lua:641>
	(...tail calls...)
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:915: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:910>

Warning: No event handler for buttonup
```
So I then downloaded the Demo, and put the HOSP folder in Applications.
Got to the setup/selector but could not choose the HOSP folder. No error, just no response from choosing/clicking okay.

**Comment by colinjmatt** [comment]
Did you extract the C.harddisk folder from the GOG package found here:

`./Theme Hospital.app/Contents/Resources/game/Theme Hospital.app/Contents/Resources/Theme Hospital.boxer/C.harddisk`

**Comment by Thorworx** [comment]
Hmm... no, I didn't dig into the .boxer package.. I'll give that a try.

Also, I keep all my games in a folder in /Applications
This is a problem for the CorsixTH.app
Minor issue, but thought I'd mention it.

**Comment by colinjmatt** [comment]
[This package](https://drive.google.com/file/d/18TRuwBWLeVtxN5-sSNWuTcyABQhJoYuY/view?usp=sharing) was built with a target of 10.10 (I have double checked), so I hope this works without you having to launch from the command line.

If the .app opens from the GUI, we can work through the other issues you're having next.

**Comment by TheCycoONE** [comment]
I think thanks to @colinjmatt we can now mark this bug as closed. Any individual issues can go in their own tickets. If the wiki documentation is insufficient, and you learn the answer, please update the wiki. It has been awhile since we had many MacOS users.
