### ISSUE TITLE
Advanced diagnostic machines can't identify diseases

### ISSUE THREAD

**Issue by davewthompson** [CorsixTH/CorsixTH#1132]
Is the logic which causes some patients not to be diagnosed ("We have exhausted all our diagnosis machines and we are not sure what this patient has") when your hospital has an X-ray, an Ultrasound, and a Blood Machine correct?

To me, this doesn't quite seem correct...

**Comment by MarkL1961** [comment]
It also depends who is diagnosing.
Have a consultant and he is more likely, a junior is less likely

**Comment by Lego3** [comment]
Each machine can only help diagnose some diseases, not all.

**Comment by MarkL1961** [comment]
Also in the later levels you will find you have to send patients to more machines before there is a diagnosis.
As for Lego3's comment, there is a table in the wiki which tells you which machines help for which disease

**Comment by Alberth289346** [comment]
There is also the research that improves machines.

Even then, I am not so sure having 100% diagnosis by whatever means is a situation that should be reachable. It would basically mean you can stop playing, as the hospital completely runs itself. It would become a movie instead of an interactive game.
