### ISSUE TITLE
Error removing litter

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1155]
Error message by handyman near to reception desk

Whether this is reproducible is unknown, when I just tried and loaded the save again the error did not happen the second time.

Links to two saves below, one at the point the error is thrown and the second is the save I loaded just before the error.

Not sure if this is related and I doubt it is I loaded the save from yesterday and started to remove the plants.  The error was thrown just after this.  I had calls dispatcher open whilst removing plants so there were no pending calls to water

Created game with savegame version 115.
Warning: Trying to remove nonexistant room build callback (function: 00000250EAEE8DE0) from humanoid (table: 00000250ED377D30).
Warning: Trying to remove nonexistant room remove callback (function: 00000250EA0E4900) from humanoid (table: 00000250ED377D30).
Warning: Trying to remove nonexistant room build callback (function: 00000250E8310F90) from humanoid (table: 00000250E5ECB020).
Warning: Trying to remove nonexistant room remove callback (function: 00000250EB44C6D0) from humanoid (table: 00000250E5ECB020).
Warning: Trying to remove nonexistant room build callback (function: 00000250EF45AFF0) from humanoid (table: 00000250E8C2A050).
Warning: Trying to remove nonexistant room remove callback (function: 00000250E893FA30) from humanoid (table: 00000250E8C2A050).
Warning: Trying to remove nonexistant room build callback (function: 00000250EAEF64C0) from humanoid (table: 00000250E8EC3D60).
Warning: Trying to remove nonexistant room remove callback (function: 00000250ED6C7E40) from humanoid (table: 00000250E8EC3D60).
Warning: Trying to remove nonexistant room build callback (function: 00000250EAEF7180) from humanoid (table: 00000250EAE35E70).
Warning: Trying to remove nonexistant room remove callback (function: 00000250E8504AC0) from humanoid (table: 00000250EAE35E70).
Warning: Trying to remove nonexistant room build callback (function: 00000250EF456850) from humanoid (table: 00000250EAAFE8F0).
Warning: Trying to remove nonexistant room remove callback (function: 00000250ECBEF470) from humanoid (table: 00000250EAAFE8F0).
Warning: Trying to remove nonexistant room build callback (function: 00000250EA7D0950) from humanoid (table: 00000250E8A4E0B0).
Warning: Trying to remove nonexistant room remove callback (function: 00000250EAC6C820) from humanoid (table: 00000250E8A4E0B0).
Savegame version is 115 (Trunk), originally it was 115 (Trunk)
Savegame version is 115 (Trunk), originally it was 115 (Trunk)
Savegame version is 115 (Trunk), originally it was 115 (Trunk)
Error in timer handler: 
C:\Users\Mark\Downloads\CorsixTH (6)\Lua\world.lua:2150: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\world.lua:2150: in method 'removeObjectFromTile'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\objects\litter.lua:98: in method 'remove'
	...nloads\CorsixTH (6)\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\entity.lua:219: in field 'tick'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\entities\staff.lua:149: in method 'tick'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\world.lua:1055: in method 'onTick'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\app.lua:1005: in function <C:\Users\Mark\Downloads\CorsixTH (6)\Lua\app.lua:1002>
	(...tail calls...)
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\app.lua:906: in function <C:\Users\Mark\Downloads\CorsixTH (6)\Lua\app.lua:901>

Trunk version 8d79e0af, save was created from an earlier version downloaded on 1st Nov 
using windows 10

@Alberth289346   Sadly I don't see any of these error messages you mentioned, so chances are this report is not of much use

https://www.dropbox.com/sh/ndakv2q87252tsq/AAAS1TXUuIiJdsLoA0_CyY9ra?dl=0

**Comment by TheCycoONE** [comment]
It looks like the litter itself didn't have a tile (x, y) https://github.com/CorsixTH/CorsixTH/blob/8d79e0afca86aee13706fce48cdcd852eeaaa642/CorsixTH/Lua/objects/litter.lua#L98

The back trace isn't completely useless.

**Comment by MarkL1961** [comment]
Maybe of some use then?

**Comment by TheCycoONE** [comment]
Could be, it will take a more detailed look. :)

**Comment by MarkL1961** [comment]
I have added the autosave for just before the error.
I can't see any litter near reception in that save or in the one with the error.
On one re-run someone arriving at reception did vomit, no error though. Might need many re-runs to re-produce

**Comment by Alberth289346** [comment]
This looks like a handyman sweeping a litter that no longer exists. Likely the handyman got the link to the litter when he accepted the call from the call dispatcher. While he walked to the spot, the litter got removed in some way. Did you build over some litter at the spot of the crash not too long before?

**Comment by MarkL1961** [comment]
No changes in that area at all Alberth289346. With the exception of removing one or two plants which were not next to the desk, but against the wall opposite that area is pretty much as it was first set up at the start of the game.  Second desk was added, but that was at least a year before then - maybe last night or even the night before
Calls for litter clearing don't appear in calls dispatcher, are they still handled that way or is it they are no longer displayed in the debug menu for calls?

**Comment by Alberth289346** [comment]
Hmm, no recent changes thus.

As for litter cleaning in the calls dispatcher, hmm, yeah, you're correct. I forgot about the second call dispatcher thing we have, called "handymantasks". For some reason that was added, instead of fixing the real call dispatcher. Iirc it was not done clean either, and the tasks are now in both systems iirc, further complicating things.

**Comment by MarkL1961** [comment]
Lovely!
So if handyman arrives to say sweep litter, could it be that if the litter is no longer there -  put brush away and move one?  (Rather than throwing an error) Or do we need to find out why there is no litter i.e. already cleaned and not updated / there was never any in the first place?

**Comment by Alberth289346** [comment]
The proper solution imho is to notify the handyman to find another job, so he doesn't walk to the old position to put his broom away. For this, we need to find the spot when the litter was removed. Afaik you can remove litter only by cleaning, or by building something on it.
Normal practice is that we do send out a notice, so either we missed one case, or the handyman ignores the notification in some way.

**Comment by MarkL1961** [comment]
Happened again on another level.
From the same link above download autosave 10.  As it opens just cancel the build and move to the main entrance.  A handyman will go to the long corridor entrance and attempt to sweep none existent litter and it throws an error
Also include the autosave from the month before as you may be able to determine what it was he was going to sweep.
Also added log file, the earlier one now has old in the title

**Comment by MarkL1961** [comment]
Got a save where I have been able to replicate the error.
Unpause and watch the handyman entering the double doors.   He will sweep an empty space and the game throws an error
https://www.dropbox.com/s/szwwdcg29l7782r/sweep%20nothing.sav?dl=0

C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\world.lua:2134: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
	C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\world.lua:2134: in method 'removeObjectFromTile'
	...rk\Downloads\CorsixTH (272635fd )\Lua\objects\litter.lua:98: in method 'remove'
	...orsixTH (272635fd )\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
	C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\entity.lua:216: in field 'tick'
	...rk\Downloads\CorsixTH (272635fd )\Lua\entities\staff.lua:149: in method 'tick'
	C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\world.lua:1051: in method 'onTick'
	C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\app.lua:1005: in function <C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\app.lua:1002>
	(...tail calls...)
	C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\app.lua:906: in function <C:\Users\Mark\Downloads\CorsixTH (272635fd )\Lua\app.lua:901>

**Comment by MarkL1961** [comment]
Another save where it can be replicated.
Load save and see litter being cleaned near to Op theatre, then by around 14th another handyman cleans the same space and the error occurs.
First time I have been able to replicate and see the original litter.

**Comment by MarkL1961** [comment]
Use the same save and try and remove the litter (coke can) before the handyman gets there.   I used a nearby bench.
This time you get the error when the first handyman tries to sweep nothing.

**Comment by MarkL1961** [comment]
The only way I can see to stop the error is to first remove the litter with an object and then pick up the handyman before he gets to that tile as this seems to cancel the cleaning call

**Comment by Alberth289346** [comment]
Right, this confirms my suspicion, handyman code is severely broken. What I think is happening is as follows, see https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/entities/staff.lua#L966 .
Handyman gets new task (lines 967-969), ie the cleaning task with the litter object. Lines 971 to 976 add a walk action to the action queue, followed by the sweep action at line 977, and 'ready' claiming at line 978 (I think). In particular, note that task.object (ie the litter) is passed into the sweep action here, at the moment he gets the assignment.
Now while the handyman is doing the first action, walking to the tile, you make the assignment invalid by removing the litter. Likely (but not checked), the litter warns the task system (but perhaps not the handyman task system?) that it got removed. The walk action is at least not aborted (or he would not arrive at the tile to sweep). The sweep task itself also doesn't check anything, it blindly assumes the object it got is still valid at the time it becomes running. See also https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/humanoid_actions/sweep_floor.lua
So the handyman sweeps the floor, and then tries to remove the non-existing litter, which fails (of course).

The root cause of this error is the assumption that a reference to an object remains valid while time progresses. That is a false assumption. A reference to some other object may become invalid at any time. Rooms, humanoids, objects, doors, etc, etc may all simply disappear without notifying you. The only things reasonable constant are walls and floor tiles, and even those change somewhat if you buy plots, for example (they get an owner).
So while plumbing this hole is easy enough, it isn't fixing the real issue: All over the place, there are references to various types of objects, where it is quite unknown if they still exist in reality.

**Comment by MarkL1961** [comment]
Refer back to my last two comments @Alberth289346 
There is litter and somehow two handymen get the task of sweeping it around ten days apart.
If the first one cleans the litter the second one can't and you get an error when he tries
If the player removes it with an object, you get the error when the first handyman tries to clean it
You can only break the cycle by removing the litter and then picking the handyman up before he gets to that tile.
Why does picking the handyman up break the cycle/cancels the call to clean?
How do two handymen get the call to clear the same litter days apart?

I agree that the system is broken, I am not sure why handymen have their own call system, it might have been that the calls dispatcher was not working as intended and this was a work around.  But I have seen two or more handymen turn up to repair the x-ray for example for some time now, doesn't throw an error though. 
I do think fixing this as it breaks the game and will be annoying to players is a must - even if it is a band aid.  The proper fix is going to be big job, I appreciate that having read through the calls dispatcher in the past.

If you want to attempt the big job and need help testing let me know.

**Comment by sgielen** [comment]
I just encountered this same error (same backtrace, at least) on the newest trunk 6a079fd0.

**Comment by Alberth289346** [comment]
Thanks for the report.
The handyman system has not changed so far, thus this was to be expected.

**Comment by mugmuggy** [comment]
In the instance of [MarkL1961 last save](https://github.com/CorsixTH/CorsixTH/issues/1155#issuecomment-266523481) I believe the first handyman arriving is getting gotoStaffRoom call, whilst performing the sweep floor action.

This removes him as an assigned handyman
https://github.com/CorsixTH/CorsixTH/blob/fe1a526b5f1da2439b71d9641165bd2dcbf1bbc3/CorsixTH/Lua/entities/staff.lua#L639-L644

As the task is still active at this point, the other handyman gets assigned andt he walk/sweep actions, but doesn't detect that it needs to interrupt (which it shouldn't as the task is in progress) so it doesn't call the existing handymans interruptHandymanTask, which it would be too late anyway, as you don't want that handyman servicing the call either.

**Comment by mugmuggy** [comment]
I've found a few other quirks which probably fix a few of the other litter clean up issues.

Here task.objects.ticks is true from the Entity constructor on litter I assume - so building over litter doesn't call interruptHandymanTask.
https://github.com/CorsixTH/CorsixTH/blob/fe1a526b5f1da2439b71d9641165bd2dcbf1bbc3/CorsixTH/Lua/hospital.lua#L2160-L2167

I've had some reliability in altering the above (just for testing the litter behaviour, didn't consider repairing/watering actions yet), and including removing the cleaning task in the action_sweep_floor_start, rather than relying on action_sweep_floor_remove_litter - which calls Litter:remove() to do the cleanup.

Litter:remove() still has to call the removeHandymanTask for when you build over.
