### ISSUE TITLE
Infinite handyman

### ISSUE THREAD

**Issue by l29ah** [CorsixTH/CorsixTH#1207]
https://dump.bitcheese.net/files/fycowag/infinite-handyman.sav
ea0e6df, Gentoo Linux, nothing interesting in the log.
This man is endlessly washing floor in the front of the reception. Cannot pick him up even.

**Comment by TheCycoONE** [comment]
Unfortunately there are a lot of these stuck individual bugs, and diagnosing what causes them is very difficult with the current design. The stuck patient / staff is a symptom and by the time it happens the cause is usually lost. If you can come up with precise steps to reproduce these issues they will likely be fixed - otherwise the chances are quite slim.

**Comment by lewri** [comment]
No response/Not enough info
