### ISSUE TITLE
Salary not increasing

### ISSUE THREAD

**Issue by UncagedFungus** [CorsixTH/CorsixTH#1275]
#### Describe the issue
After getting to the end of the first year of a new level, I notice my salary is on a par with the other three hospitals and not anywhere near what I had been offered.
Currently at Simpleton, moved with offer of >$50,000 after curing over 3000 patients and having over $3,000,000. 

#### Save Game
https://drive.google.com/file/d/1JICaEZLPr9qppA83n_NZs9aljJdBXl9e/view?usp=sharing
https://drive.google.com/file/d/1E3-KuAiNDAwkkrjuxPuT7Eb2geMb5nAO/view?usp=sharing

#### Expected Behavior
Salary keeps increasing as you move up levels and stays increased.

#### System Information
**CorsixTH Version:** .60
**Operating System:** Windows 8.1
**Theme Hospital Version:** CD

#### Gamelog.txt
Empty action queue!
Last action: walk
stack traceback:
	...ettings\user\My Documents\HOSP\Lua\entities\humanoid.lua:546: in upvalue 'Humanoid_startAction'
	...ettings\user\My Documents\HOSP\Lua\entities\humanoid.lua:672: in method 'finishAction'
	...ngs\user\My Documents\HOSP\Lua\humanoid_actions\walk.lua:152: in local 'timer_function'
	...ments and Settings\user\My Documents\HOSP\Lua\entity.lua:219: in method 'tick'
	...uments and Settings\user\My Documents\HOSP\Lua\world.lua:1075: in method 'onTick'
	...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:1000: in function <...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:997>
	(...tail calls...)
	...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:901: in function <...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:896>
The humanoid was told to leave the hospital...
Warning: Trying to remove nonexistant room build callback (function: 000000744F2758A0) from humanoid (table: 000000744DC3E8B0).
Warning: Trying to remove nonexistant room remove callback (function: 0000007456DBBB50) from humanoid (table: 000000744DC3E8B0).
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 0000007454AFE990) from humanoid (table: 0000007447B975A0).
Warning: Trying to remove nonexistant room remove callback (function: 0000007448F0D420) from humanoid (table: 0000007447B975A0).
Warning: Trying to remove nonexistant room build callback (function: 0000007454AFCFB0) from humanoid (table: 0000007444A5D7E0).
Warning: Trying to remove nonexistant room remove callback (function: 000000744FC11EA0) from humanoid (table: 0000007444A5D7E0).
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Error in timer handler: 
...cuments and Settings\user\My Documents\HOSP\Lua\room.lua:323: Handyman arrived is on call but not arriving to the designated room
stack traceback:
	[C]: in function 'assert'
	...cuments and Settings\user\My Documents\HOSP\Lua\room.lua:323: in method 'onHumanoidEnter'
	...ngs\user\My Documents\HOSP\Lua\humanoid_actions\walk.lua:356: in local 'on_next_tile_set'
	...ngs\user\My Documents\HOSP\Lua\humanoid_actions\walk.lua:191: in function <...ngs\user\My Documents\HOSP\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	...ments and Settings\user\My Documents\HOSP\Lua\entity.lua:219: in field 'tick'
	...d Settings\user\My Documents\HOSP\Lua\entities\staff.lua:149: in method 'tick'
	...uments and Settings\user\My Documents\HOSP\Lua\world.lua:1075: in method 'onTick'
	...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:1000: in function <...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:997>
	(...tail calls...)
	...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:901: in function <...ocuments and Settings\user\My Documents\HOSP\Lua\app.lua:896>

**Comment by MarkL1961** [comment]
Can you attach your save please?

**Comment by MarkL1961** [comment]
I have tested this out on a later version and it does appear to be broken as the salary offer should carry over into the next level unless you have cheated and it is no longer doing this

**Comment by UncagedFungus** [comment]
Of course I haven't cheated.  If I had I wouldn't have been offered an increased salary.

Attach my save?

**Comment by MarkL1961** [comment]
I am not saying you have cheated.  I explained how it should work and did work.

**Comment by UncagedFungus** [comment]
https://drive.google.com/open?id=1JDN0LH2vBuJI3AGeub8syhYjIvuuNcHI

**Comment by MarkL1961** [comment]
I've been looking through the code and there are other factors that affect your score/salary.
The number of deaths and your reputation also have an impact - look at lines 1070 ish onward.
However I can't see how that would have a negative impact as it looks to me that at the very least you would get +30 each month and no more than +300.

`  -- add to score each month
  -- rate varies on some performance factors i.e. reputation above 500 increases the score
  -- and the number of deaths will reduce the score.
  local sal_inc = self.salary_incr / 10
  local sal_mult = (self.reputation - 500) / (self.num_deaths + 1) -- added 1 so that you don't divide by 0
  local month_incr = sal_inc + sal_mult
  -- To ensure that you can't receive less than 50 or
  -- more than 300 per month
  if month_incr < self.sal_min then
    month_incr = self.sal_min
  elseif month_incr > self.salary_incr then
    month_incr = self.salary_incr
  end
  self.player_salary = self.player_salary + math.ceil(month_incr)  `
Question now is why does your salary reduce from offer at the end of one level to the end of year 1 in the next?   Perhaps there is another factor I am now aware of - this needs some investigation or input from someone who already knows the answer.
I have compared relevant code for offer and it appears to be unchanged from earlier versions (0.4 and 0.5)

**Comment by TheCycoONE** [comment]
I haven't had time to look at this issue yet (been focusing on the CMake improvements), but is it possible that the bonus shown on the fax isn't being rolled back into the salary?

**Comment by DavidFair** [comment]
I've opened a pull request which should fix this for new games. 
Previously we set an incorrect flag saying we are playing the campaign, as described in #1308 .
@UncagedFungus because this flag can't be set on existing saves easily it is likely you will need to start a new campaign if the changes are merged to resolve this.
