### ISSUE TITLE
Patients leave ward too early when Nurse is picked up

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1277]
#### Describe the issue
Nurse leaving ward (at least on pickup) aborts the patients stay. Upon picking up the nurse from the ward, patients leave immediately when they should actually stay the visit.

#### Steps to Reproduce
1. Wait for patient to enter ward.

2. Pickup nurse.

3. Watch patient leave.

#### Save Game
[nursepickup.zip](https://github.com/CorsixTH/CorsixTH/files/1456904/nursepickup.zip)
Patient is already going to bed here, pick up nurse asap, patient leaves around the 27 Mar. Reload game, leave nurse along patient jumps out on the 31 Mar.

#### Expected Behavior
Origin TH leaves the patient in the room for the diagnosis to complete. Nurse only really required for patient to enter ward. Likewise a tired nurse should be able to leave the ward with patients.

#### System Information
**CorsixTH Version:** 0.60 + trunk

**Operating System:** Windows 7

**Theme Hospital Version:**  Origin

#### Gamelog.txt
None created

### Additional Info
None

**Comment by MarkL1961** [comment]
I have a feeling that this is intentional ( @Lego3 ) might be able to confirm this.
How would the patients get diagnosed in an unstaffed room?
Yes TH did it this way, but that may have been a bug, like the one where you failed an epidemic just because a patient left one part of your hospital to go to another part.
The staff in a room also play a part in the speed of the diagnostic process, the higher the skill level the faster the process is.
What I do think could be an improvement is if the nurse leaves the room the patients go back to the  queue.  If the nurse is ready for a break then if there is no spare nurse patients wait outside until she comes back.

**Comment by TheCycoONE** [comment]
Staying in the room without the diagnosis continuing until the room is staffed again sounds like fine behaviour to me, both for game play and realism.

That said I haven't looked at how it would be implemented.

**Comment by mugmuggy** [comment]
For the diagnosis progress
Code is precalculating the length of stay based on nursecount at the time patient enters
https://github.com/CorsixTH/CorsixTH/blob/6e81bda1485e9ab40053623394d84f64e1544bff/CorsixTH/Lua/rooms/ward.lua#L140-L141

If we removed the division then in the loop_callback decremented length by the nursecount, which has to be recaculated (ie this breaks old save) the same thing is achieved, just it allows the diagnosis to stop/start/increase/decrease
`self:countWorkingNurses()`
`length = length - self.nursecount`

Then for not having patients leave until the end.
https://github.com/CorsixTH/CorsixTH/blob/6e81bda1485e9ab40053623394d84f64e1544bff/CorsixTH/Lua/room.lua#L569
to
`if not self:testStaffCriteria(self:getRequiredStaffCriteria()) and self.room_info.id ~= "ward" then`

Then it would be just allowing tired nurses to leave which I haven't looked at yet.

**Comment by lewri** [comment]
This is normal behaviour as far as I remember. If a room becomes unstaffed the patient (or patients) will leave the room until it is staffed again (like a forced interrupt). However, I wouldn't expect the nurse to leave at her own accord if a patient was present (instead wait until diagnosis completes and do not allow new patients to enter).  

Are you saying the nurse just gets up and leaves while people are present? This shouldn't happen... And worth looking at if it's the case.

Pausing diagnosis is a nice alternative however, until a nurse returns. But surely if you were picking up a nurse and putting her somewhere else it was for a reason right? I think it would be normal in that case to interrupt any diagnosis happening.

**Comment by mugmuggy** [comment]
I checked the Origin one, nurses are allowed to leave (either picked up or tired) and diagnosis continues. With 0.60 and trunk, you pick up the nurse and all patients will leave paying for the service, even though they didn't stay the full length of the stay. Patients can't enter the ward unless its occupied by a nurse as expected.

With the Origin one, if you have a pharmacy and ward, and only one nurse eventually the nurse can leave and attend to the queue in pharmarcy also whilst patients are still in the ward and there is a queue.

However, I believe the nurse may have a tendency to only change rooms when all the beds are full or the queue for ward is empty.

**Comment by overlordchaos** [comment]
i must agree with lewri. this is normal. its a game wide rule. if the staff member leaves the room (or you pick him up) the patient leaves. the theory is that once the staff member goes away untill a new one comes along, the room its closed down. its like closing down/opening a store. once it closes it closes once it opens, it opens. this was made most likely to avoid bugs such as a doctor/nurse leaving while the patient remains. maybe the new staff member would come and the person would not leave (maybe stuck) so you cannot delete the room. i am guessing it is something in that area. fixing a complicated bug with a simple solution.
my personal opinion its that is fine. thats how the game always worked and its not an issue to me its a mechanic i am used to. plus maybe if corsix tweaks it, may create a bunch of new bugs such as the one i just mentioned.

**Comment by mugmuggy** [comment]
I've already ascertained this was at least a 'feature' in the original. I just happened to pick up the nurse in CorsixTH, patients leave and pay up. Effectively a cheat mechanism if you want to look at it that way, allowing you to build a smaller ward than you might normally need to cater for, pick up the 'last remaining' nurse and everyone disappears and pays up a little for your effort too.

When I went to replicate in TH they stay and diagnosis finished and they leave even without the nurse there. I also ascertained the nurse will leave when tired - when beds are full or if queue is empty (beds can be used), to deal with other calls - they'll return to ward when the next room they are in has no queue, and are called to the ward again.

Likewise dropping another nurse into the room as a patients stay is about to start, counts the nurse, when the count should be the lesser of nurses and desks (this is just a timing thing, with onHumanoidLeave not executing at that point).

Likewise there is also this comment
https://github.com/CorsixTH/CorsixTH/blob/b9339ffcd37aa3e50e85e3aefe62d7dd4652af74/CorsixTH/Lua/rooms/ward.lua#L127-L128
And that behaviour is inconsistent with the original, and obviously not what happens now. As pointed out https://github.com/CorsixTH/CorsixTH/issues/1277#issuecomment-343266286 and my following comment, there is potential for a medium here. Noting the difference between the ward and the other nurse rooms, is that the nurse doesn't interact with the object the patient is using - which probably does allow them to leave.

**Comment by TheCycoONE** [comment]
In cases without clear consensus we default to original game behaviour as a matter of rule.

At this point, if someone is looking to address this issue, they should replicate the original and allow nurses to leave while patients stay in the beds and continue to be diagnosed.

@mugmuggy from your tests of the original game, could patients leave without a nurse present?

**Comment by mugmuggy** [comment]
Yes, diagnosis can continue without a nurse present. Patient leaves at the end. No new patients can enter of course. Fairly simple for the tiredness/pickup scenario, I've already played with that with a few edits. Handling calls to say pharmacy, and upon leaving ward, getting that call to stay in ward tripped me up at the moment

**Comment by lewri** [comment]
I know it's rather late but maybe I should weigh-in again. If the ward is a diagnosis procedure (in this case an observation), we would expect the results of our observation to be recorded by the nurse. Instead, I don't think a patient should leave without a nurse present so the nurse emulates signing-off the patient. The only bug bear of this is if we end up with patients stuck at the ward because no nurse is available.

However, I  will back down about the other issue, it makes sense for a nurse to come/go while operating the ward.

**Comment by daiscog** [comment]
I've just experimented with the original game and can confirm that a nurse was only needed in a ward for the patient to be admitted.  Once in, the nurse can be removed and the patient still completes their visit as normal, including paying before leaving.

Given a ward can have many patients in it at once, this makes sense to me, otherwise the nurse might never get the opportunity to leave.  The nurse shouldn't have to wait for all beds to be vacated before she can go to the staff room, chase epidemic patients, or whatever.

**Comment by mugmuggy** [comment]
For your points, only the first one holds true to the original. Second and third points don't hold true to the original and for 4th I haven't confirmed either way the case. When I was mucking about with this, I had issues with the calls dispatcher where I had a pharmacy and ward, one nurse and enabled the nurse to leave. The calls dispatcher was always attempting to recall the nurse (as it is also the closest room once she leaves and gets a higher score) and she wasn't allowed to return to the room she was leaving or something like that.

I've noticed that potentially the stays in a ward are too short also in Corsix than the original - I'm thinking that time in the ward is not linked to the quality of your staff member, but only diagnosis progress see #1340. I just haven't gotten around to testing this theory as yet.

**Comment by Brainsample** [comment]
Hi Mugmuggy,

There are several things to consider. Currently in CorsixTH, all patients are magically cured when the last nurse exits the room, which is an easy exploit. It looks like in the original game, a nurse only had to be present when a patient is admitted, which is also a bit of an exploit. Possibly the original coders had to settle for this behaviour because time ran out, the game had to be released.

Realism in computer games is one thing, but it doesn't always make for balanced gameplay. Personally, I just wanted intuitive and interesting gameplay, rewarding the player for playing well.

=======

It's easy to tweak the behaviour of this code:

- Make (some) progress when no nurse is present.
Initialize nurse_force with a positive value
```lua
local nurse_force = 1.0	-- The total amount of work the nurses do
```

- Adjust the effect of the number of nurses.
Change numerical value 
```lua
nurse_force = nurse_force + 0.12345 + nurse_quality
```

- Adjust the effect of service quality.
Add a multiplier
```lua
nurse_force = nurse_force + 1.0 + nurse_quality * 0.12345
```

- Adjust the effect of number of patients.
Add a multiplier
```lua
self.healing_amount = nurse_force / (1 + self.patient_idx * 0.12345)
```

- Change the base time (and spread) for a patient to stay in bed.
```lua
local amount_to_heal = math.random(1234, 5678)
```

- Remove the effect of diagnosis quality.
Delete the 5 lines involving the variable "best_staff".

=======

Today I did a test with very long healing times in CorsixTH. A tired nurse will not go to rest when there are patients in the ward. So I looked it up, and found another change in my code.
It's in \Lua\entities\staff.lua Staff:checkIfNeedRest() line 582:

```lua
if (self.staffroom_needed and (room and (not room:getPatient() or room.room_info.id == "ward")) or not room) or (room and self.going_to_staffroom) then
```

The ward is the only room for which this exception applies.

=======

Currently in CorsixTH, when the last nurse exits the ward while there's a patient, the callsdispatcher calls a new nurse to the ward. This behaviour is correct, in my opinion.

**Comment by mugmuggy** [comment]
I had assumed from https://github.com/CorsixTH/CorsixTH/issues/1277#issuecomment-347523238 that the original behaivour would be the favoured approach here, as there isn't yet a clear consensus. Your changes cover the nurse leaving when tired, but not the answer another call scenario necessarily - ie Beds full, nurse can leave to go to pharmacy, patients finish in ward and leave once their time ticks down, nurse will return if there is a call dispatch to return to the room and the pharmacy queue size is 0.

I originally found the exploit of picking up the nurse and having the patients leave immediately, then started checking what the original did and found this other behaivour. At worst then the original ticks down the _healing_amount_ at the rate of 1 per tick, but I have a feeling the original just does this no matter what - just I haven't got around to trying to track it down.

**Comment by Brainsample** [comment]
Hmmm, so that would mean nurses completely ignore patients once they're in bed?
That's not very elaborate. :)

**Comment by overlordchaos** [comment]
i think the ward NEVER did anything. it was truly a time waster for the game. EXCEPT diseases that got cured in the ward. but in cases when the cure is for example, ward then surgery, the TRUE cure is the surgery NOT the ward. it would require someone to play the original on the final level (since you have all diseases on) and obserb if my theory is correct. i do remember on the original the nurses only where seated on the desktop OR walking around the beds. but they did not have an animation to check actively on patients. so yeah i think the nurse ignores the patient they are "decorative" at best.

**Comment by TheCycoONE** [comment]
I am ok with the behaviour @MarkL1961 describes, with the diagnosis progress updated every hour while the nurse is present (or with a chance of being updated every hour depending on how the numbers work out) based on the quality of the nurse and the number of patients in the ward.

**Comment by Brainsample** [comment]
Thank you for the clarification, the behaviour you describe makes perfect sense. 
The code I wrote produces this behaviour, but it does so every tick, not every hour.
CPU load is minimal.

=======

The function shouldHavePatientReenter() can be repaired, but it can also be removed.
Since the ward is the only room that works like this, the exception can be hardcoded in  
\Lua\room.lua onHumanoidLeave()

```lua
	-- Make patients leave the room if there is no longer enough staff
	if not self:testStaffCriteria(self:getRequiredStaffCriteria()) then
	  local call_for_new_staff = false
	  for room_humanoid in pairs(self.humanoids) do
		if class.is(room_humanoid, Patient) and not room_humanoid:hasLeavingAction() then
		  call_for_new_staff = true
		  if self.room_info.id ~= "ward" then
			self:makeHumanoidLeave(room_humanoid)
			room_humanoid:queueAction(self:createEnterAction(room_humanoid))
		  end
		end
	  end
	  -- Call for staff if needed
	  if self.is_active and (call_for_new_staff or self.door.queue:patientSize() > 0) then
		self.world.dispatcher:callForStaff(self)
	  end
	end
```

This part of onHumanoidLeave() had to be fixed anyway.

**Comment by TheCycoONE** [comment]
`tick` and `hour` are likely the same thing in this case. `tick` is used both for an in game tick, also called an `hour` (even though there are 50 in a day), and a system `tick`. If you were using the wrong `tick` then the rate of progress would depend on the game speed - which would clearly be bad.

**Comment by Brainsample** [comment]
That's a good point!
It was easy to test, game speed did not affect the rate of progress.

=======

The code is also savegame compatible, though patients who are saved in bed will still behave in the old way.
It's not a real problem.

**Comment by mugmuggy** [comment]
I meant more that the original behaivour would be the likely outcome as concensus hadn't been reached. Everything I've noted in this issue is observed, besides the reference to the Improving diagnosis process.

There are a few downsides to not progressing the diagnosis.
- patients health continues to decline
- staff have to respond to calls, could be issues as staff sometimes seem to wander
- need to then check a staff member is in the room, whereas an empty room will indicate that no staff or no queue - admittedly there are other cues given

The nurses leaving probably wasn't noticed as much as the early levels you could cover it easily and probably have enough staff - a lot of the game is easily ignored and just continue. Later levels,  management goes up and its probably advantegous not to have to additionally micromanage the wards in addition to the doctors.

For example, diagnosis progress could continue but patient unable to leave until room is staffed again, slightly different to pausing progress, but still suffers from the downsides.

As Brainsample includes the getServiceQuality and mentions fatigue, fatigue in that regard impacts it linearly but you don't linearly become tired, hence in the diagnosis progress, the gbv.Tired limit is used to start to have that negative influence. Then do you double (reducing the remaining tick times by a half or some other patient related factor) ensuring the patients do leave and continue on but given a penalty still without having the micromanagement.

**Comment by Brainsample** [comment]
If people want to test this new ward, the attached file "ward_basics.zip" contains the necessary files.
Just copy the the Lua folder into a clean installation of CorsixTH v0.61, and confirm all prompts.

[ward_basics.zip](https://github.com/CorsixTH/CorsixTH/files/1885905/ward_basics.zip)

**Comment by lewri** [comment]
A commit has been mentioned for this, but was it ever implemented to CorsixTH?

**Comment by TheCycoONE** [comment]
No, the PR was never sent to us.

**Comment by Brainsample** [comment]
Howdy folks,

Staying close to the original TH was never my personal plan. What I really wanted at first was an intelligent staff-AI. Then I also made 12 different walking speeds, a new diagnosis system that's never 100% accurate, a death-clock, and many more things that do not fit in the Corsix project.

And then there was the ward, broken and boring. I wanted the ward to be more interesting and challenging. The code I shared is my own view of what's fun, realistic and balanced.

I hope you can find consensus on the desired behaviour.
Thank you Alberth289346 for going over the code with a fine comb in #1277. :)

And again, sorry for not being able to work in the repo.
My dyslexia explodes every time I try, lol.

**Comment by colinjmatt** [comment]
Hey @Brainsample, a little off topic, but you should join our Discord if you feel like discussing things like this with us. Find all our social media links in our [Wiki](https://github.com/CorsixTH/CorsixTH/wiki)

**Comment by lewri** [comment]
`When she leaves the room the patients stay, but don't heal until a nurse returns`
Just to ask, @tobylane , will patients still continue with the diagnosis process if a nurse is vacant; but not be released until a nurse returns?

**Comment by tobylane** [comment]
They don't, ward.lua:141 of #1706 zeroes the healing factor when there's no nurses.
