### ISSUE TITLE
Please provide stand alone binaries 

### ISSUE THREAD

**Issue by xcom169** [CorsixTH/CorsixTH#1304]
Please provide stand alone binaries of the game, so players without admin rights still can run it

**Comment by overlordchaos** [comment]
@xcom169 may i suggest, to install the game to a non-admin folder? (dont install on program files) change the path to some user folder. for example to the download folder or links folder. those are useless if you ask me on windows. do something like links\theme hospital so it wont scatter files over the links folder on the user folder. in that way you dont need admin rights (i think)

**Comment by wolfy1339** [comment]
The way the installer currently works is that it's requesting Elevated Privileges (Admin) when you run it. Doesn't matter what folder or anything else.

**Comment by TheCycoONE** [comment]
A standalone binary won't be an option, but zip files are available through appveyor that can be run from whatever directory they are extracted in.

I can either link, or copy those zip files to the release page. The Visual C++ Runtime would still be required, independently.

Would this satisfy your requirements?

**Comment by wolfy1339** [comment]
That still wouldn't help the use case describes
> players **without admin rights**
Since they don't have admin rights, they won't be able to install Microsoft Visual C++ Redistributable.

The Visual Studio C++ Redistributable could be statically linked instead, removing the dependency altogether. That would actually completely fix their use case.

But, I agree stand-alone binaries (ones from TravisCI and AppVeyor) should be linked to/copied over to the release page

**Comment by TheCycoONE** [comment]
We can't legally statically link some of our dependencies because we are not a GPL project.

Mixed linking is possible in some cases but not a game I feel like playing if it works at all in our case.

Including the msvcr*dll is an option I believe (though I have to go over the license to see the restrictions): https://www.visualstudio.com/en-us/productinfo/2017-redistribution-vs

**Comment by xcom169** [comment]
Maybe could you set up the installer, to use %appdata% if the user doesn't have elevated access to the computer?

**Comment by lewri** [comment]
I decided to query the license terms for Visual Studio 2017 and looks like Microsoft has no problem with you including those redist DLLs in the game files.

A query put into stackoverflow has pointed out using 'locally deployed' files however, can get messy because it would mean CorsixTH has to maintain them. Again, it suggests using static links. I'm not sure why you can't static link though, I have no idea and trying understand why you can't hasn't really helped.

https://stackoverflow.com/questions/35097193/can-i-bundle-the-visual-studio-2015-c-redistributable-dlls-with-my-applicatio

**Comment by overlordchaos** [comment]
@lewri up to my understanding, this is done cause MANY pc games installations has bundled it, and when MS started to "allow" the support apps for games, it did it out of charge, considering if you where going to add to the developer and/or the final consumer the extra money for some sort of MS license to use those free downloads... lets just say they allow it cause if not windows WOULD NOT BE a gaming platform. it would be more expensive than purchase a console with a single fee for the game.
imagine having your games 2x as expensice cause the dev and you need to pay a "redistribution" license to MS to get visual studio, another one for directX, another one for framework... even if the cost to the final consumer was $1 per redistributable... you might end up needing to pay 5 extra dollars PER game...

**Comment by TheCycoONE** [comment]
@lewri I know including the non-debug dlls from the redistributable is allowed.

The only reference I see to static linking in that stack overflow is talking about standalone executables. CorsixTH depends on lua files and other resources outside of the executable anyway, so all we would gain from static linking is potentially a little bit smaller download from dead code removal.

There is nothing blocking this issue. A portable x86 zip file for v0.61 can and will eventually be provided.

**Comment by TheCycoONE** [comment]
Done.
