### ISSUE TITLE
Jukebox preventing save

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1385]
#### Describe the issue
Same issue as #543, cannot save games, autosave or manual if jukebox is open.

#### Steps to Reproduce
1. Open Jukebox, wait for next month to tick over

2. Console fills with many 'Unhandled argument to th_getfenv'
followed by
```
nil     <no name>
Error while autosaving game: Lua\persistance.lua:247: Can only persist non-empty
 userdata if they have a __depersist_size metafield
```
If you have another dialog open an Information window is displayed with the error above also.

#### Expected Behavior
Saves should be created.

#### System Information
**CorsixTH Version:** *trunk*

#### Additional Info
I have a PR in the works if anyone else can confirm they indeed have the issue.

**Comment by TheCycoONE** [comment]
Haven't looked yet but I'm curious what your PR does, and if this only affects certain lua versions. th_getfenv is completely different in Lua 5.1/LuaJIT than Lua 5.2+

**Comment by mugmuggy** [comment]
Admittedly it might not be the most elegant. I switched to the setToggleState calls, as if you engage looping, then click a toggle it becomes `enabled`, then undo the loop it was toggling the state again and combined with the possibilty of going back to a save the ui became inconsistent, but the update in draw probably would have corrected that anyway.

I must admit these persisted funtions and the use of them confuses me a little but I guess one of the additional parameters was preventing it working.

**Comment by TheCycoONE** [comment]
If you're curious, what you did was remove 'info' which is userdata (i.e. a c++ class/struct) from the upvalues (variables from outside a function, stored with and used in a function) from the persistable jukebox_toggle_track function. Now the only upvalue that function stores is the index i.

Evidently that userdata was not properly configured for storage. There are likely still problems with persisting the jukebox; e.g. if the music list changes between loads. 

I'm ok with merging this PR as is, because I think it's a bit cleaner, but preferably UIJukebox would be excluded from saves, and the callback wouldn't need to be persistable. Since this hasn't changed in many releases, it's probably safe to not even add a contingency for old saves.

**Comment by MarkL1961** [comment]
As you cannot save with the jukebox open I tend to agree there won't or should not be any issues with saves. (I don't think you ever could)
I am not sure that anyone would even notice that the music was changed from a save to loading it later and as it would only happen if you had the jukebox open at the time it is even less likely to happen

**Comment by mugmuggy** [comment]
The 'draw' changes effectively take the audio.background_playlist and updates the UI state to match.
So if you open in a separate run - background_playlist is reset to all tracks, ui will reflect that. Another happy accident was that if just before the end of month, and it saves state, then you modify it the next month, then revert to the save, it will update the playlist to match the latest. But yeah not persisting the UI entirely is probably an ok idea too.

**Comment by lewri** [comment]
Link PR #1386
