### ISSUE TITLE
FPS Drop on Zoom

### ISSUE THREAD

**Issue by mlugg** [CorsixTH/CorsixTH#1420]
#### Describe the issue
The FPS gets dropped whenever you zoom. The effect is unnoticeable at first, but it amplifies as you zoom, so after playing for a while the game slows down very noticeably when zooming, sometimes to
the point of freezing entirely.

#### Steps to Reproduce
1. Load into any save

2. Use the scroll wheel to zoom in and out a lot

3. The game will slow down and eventually crash

#### Expected Behavior

That this doesn't happen.

#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Debian Stretch

**Theme Hospital Version:** Torrented because I own the game on Origin but it wasn't working in my VM - probably a CD rip

#### Gamelog.txt
gamelog.txt was not present
![image](https://user-images.githubusercontent.com/7289241/41258185-31f997c8-6dc7-11e8-9d05-f691b062ea1b.png)

**Comment by TheCycoONE** [comment]
If you can, try the latest master. There has been some effort to improve memory management recently. I am assuming the slowdown you are seeing is from leaking video ram.

**Comment by mlugg** [comment]
I'll try it out later, thank you :)

**Comment by mlugg** [comment]
Sorry about the late response - the issue still appears to be present on master

**Comment by mrtnptrs** [comment]
Could you try to use your Origin version instead of the Torrented version? If you use an ISO file in combination with a mounting application, it could cause the slowdown when loading assets of the game. Also, many things can be wrong with an illegal version, so, I would try the non-torrented version anyways. Could you also provide the specs of your pc/what hardware your pc has?

**Comment by mlugg** [comment]
I'll try and get the Origin version today. My specs are a Sapphire Radeon RX 480 8GB GDDR5 graphics card, an AMD A8 5600K CPU, and 8GB of Corsair Vengeance DDR3 RAM.

**Comment by TheCycoONE** [comment]
From @mlugg 's description the game got slower every time he zoomed, so even resetting the zoom wouldn't help. You'd have to compare a game you started from the beginning without playing with zoom, and a game where you frequently switch zoom levels.

**Comment by CyberKiller40** [comment]
I didn't have much time to play in the past few days, but I tried the game yesterday. It seems I might have been mistaken, the slowdown doesn't seem to be tied to the zoom level at all. On the other hand the game is sluggish overall. I thought for a moment that this might be due to running it through GOG galaxy (I planted the corsixth.exe in place of dosbox.exe inside the game directory in order to get the playtime counted on GOG), but running directly didn't help.

Sorry for misleading you, however I could use some tips on how to get better game performance. My machine should be able to run it blazing fast.

**Comment by TheCycoONE** [comment]
@CyberKiller40 what screen resolution are you running the game at?

**Comment by CyberKiller40** [comment]
Nothing much actually, just 1366x768, I can play other 2d games very easily at this resolution.

**Comment by swingflip** [comment]
Just to say we have encountered this issue on a port to the playstation Classic I have done. We are limited to 1gb DRAM, ArmV8A35, 1.5ghz quad core. 

It appears zooming in and out drops the fps dramatically especially with the mouse wheel then the binary crashses due to lack of memory. Latest master build FYI

**Comment by TheCycoONE** [comment]
@swingflip are you able to trace where the memory is going. Valgrind or asan?

**Comment by swingflip** [comment]
@TheCycoONE I will run it through debugger when I get a chance and get back to you

**Comment by swingflip** [comment]
Sorry haven't got much time but ran it against STRACE for you and recorded capture card. (Headphone warning. I forgot spotify was running Sorry!)

[corsixth.log](https://github.com/CorsixTH/CorsixTH/files/4375609/corsixth.log)

https://www.youtube.com/watch?v=gmoq5i5Gr4Q

(Performance is impacted as I am running via STRACE)

**Comment by TheCycoONE** [comment]
This is likely due to the way zoom is implemented; it's not particularly efficient with respect to video memory.

**Comment by mlugg** [comment]
Hi, I totally forgot about this issue, but I've revisited CorsixTH recently and am not encountering this issue anymore. Therefore, I'm going to assume it's been fixed, potentially by the linked PR. Apologies for leaving this stale issue open for so long!
