### ISSUE TITLE
FHS compliance - 2 issues

### ISSUE THREAD

**Issue by mattmill30** [CorsixTH/CorsixTH#144]
1. CorsixTH binary is installed into /usr/share/games/corsix-th, with a symlink in /usr/games.
   The binary should be installed into /usr/games directly.
2. Original data folders should be expected in /usr/share/games/corsix-th.
   a) If the original data folders (and files within) can't be located the 'HOSP location' dialog should then be displayed.
   b) Original folders (e.g. LEVELS) should be checked for before new folders (e.g. Levels), to avoid 'HOSP location' always being displayed (and never satisfied) when both folders are stored in /usr/share/games/corsix-th

**Comment by TheCycoONE** [comment]
I'm working on this now.

My thoughts are that a distro package should be able to install the CorsixTH executable in
/usr/bin/corsixth and the rest of the CorsixTH platform independent resource files under a directory configurable in CMake e.g. (/usr/share/[games/]corsixth).  I am currently investigating the best way to handle this in CMake - I'm sure it's a common requirement for programs in posix environments.

HOSP data from the original game will not be included by distributions as that would be a copyright violation.  Since that location is prompted at first run I don't see anything to do there, the user is free to store it in /home/user/theme-hospital or /usr/share/local/theme-hospital or anywhere else they feel is appropriate.

**Comment by Lego3** [comment]
Have you looked at this anything more, TheCycoONE?

**Comment by TheCycoONE** [comment]
Not recently. I know the fix but I haven't prioritized it. I suppose anyone else could take it over if they wanted.

**Comment by TheCycoONE** [comment]
Part 1 was addressed in 0.62, part 2 is partially addressed. The default location of original game files is not a clear issue. Closing this.
