### ISSUE TITLE
Game froze while playing the game, error says something about timer

### ISSUE THREAD

**Issue by kymark12** [CorsixTH/CorsixTH#1555]
#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Error should occur immediately after loading the save file

#### Save Game
https://drive.google.com/file/d/1zHfi_wPmgimmxPLPbzea3XeINAJMfoyJ/view?usp=sharing

#### Expected Behavior
The game should still run normally or as expected

#### System Information
**CorsixTH Version: 0.63

**Operating System:**
Windows 10

**Theme Hospital Version:**
Origin

#### Gamelog.txt

```
humanoid - class: Alternate Male Patient
Warmth: 0.187   Happiness: 0.971   Fatigue: 0.000  Thirst: 0.361  Toilet_Need: 0.141   Health: 0.000
Actions: []
stack traceback:
	[C]: in function 'error'
	Lua\entities\humanoid.lua:906: in method 'getCurrentAction'
	Lua\hospital.lua:698: in method 'countSittingStanding'
	Lua\hospital.lua:728: in method 'checkFacilities'
	Lua\hospital.lua:982: in method 'onEndDay'
	Lua\world.lua:1004: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
Savegame version is 134 (v0.63), originally it was 134 (v0.63)
Error in timer handler: 
Lua\entities\humanoid.lua:906: Action queue was empty. This should never happen.
humanoid - class: Alternate Male Patient
Warmth: 0.187   Happiness: 0.971   Fatigue: 0.000  Thirst: 0.361  Toilet_Need: 0.141   Health: 0.000
Actions: []
stack traceback:
	[C]: in function 'error'
	Lua\entities\humanoid.lua:906: in method 'getCurrentAction'
	Lua\hospital.lua:698: in method 'countSittingStanding'
	Lua\hospital.lua:728: in method 'checkFacilities'
	Lua\hospital.lua:982: in method 'onEndDay'
	Lua\world.lua:1004: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by mugmuggy** [comment]
Essentially a dupe of #1439. Autosave before this as it was only a few days after would help identify the root cause if the patient was technically dead before entering the room, or after. My change in #1476 (room:dealtWithPatient) increases the risk this could occur, but as disucssed in #1431 if a callback for a room exists, and the patient has just died, the callback could complete which incorrectly sends them to the room when they should be dead.

Though patients health history seems high enough to be surviving, something has set the patient going_home flag to true, and the dealtWithPatient has been called after (this will finish the 'idle' action) and there would be nothing left afterwards. Reloading the save is after the fact. The patient does seem to have died as treatment seems unsuccesful going by that health history and the mood icon is set to dead but that should occur after the check in dealtWithPatient.

**Comment by kymark12** [comment]
Thanks, I hope there's a fix for this, but I'm glad it's not a regular occurrence.
