### ISSUE TITLE
MacOS ARM/Apple Silicon support for CorsixTH

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1753]
This is more a discussion to look at any potential conflicts that may arise with the new Macs now having ARM processors in them.

Are we currently in a position to support ARM?
What additional builds/requirements would be needed for the ARM environment?
Are there any resources currently available to help with transition? (e.g. can homebrew resources help?)

Do we expect to have this support in place for 0.65?

**Comment by tobylane** [comment]
Homebrew will have a self hosted arm CI soon, well before the services we can use (Travis, Azure Pipelines). Corsixth is due to be built in that. I will use what CI comes out but will have to rely on others testing it. 

Homebrew has built corsixth on Intel big sur successfully but the logs are unavailable. I can do the same on Pipelines if wanted.

**Comment by TheCycoONE** [comment]
I run CorsixTH on linux on aarch64 frequently,  I don't anticipate problems beyond whatever the packagers need.

**Comment by colinjmatt** [comment]
For now, whatever @tobylane has planned for Arm will be how it needs building. However, we don't have any way of testing as of yet. Donations of an Apple Silicon product greatly appreciated :)

**Comment by lewri** [comment]
If I remember correctly from a previous discussion, CorsixTH is now working via Homebrew on MacOS ARM.

**Comment by lewri** [comment]
Happy to close this now that we have plenty of evidence this should run fine with ARM.

**Comment by lewri** [comment]
Homebrew have now published (likely a while ago) CorsixTH on ARM. Unpinning now
