### ISSUE TITLE
Possible null pointer dereference

### ISSUE THREAD

**Issue by ZanyXDev** [CorsixTH/CorsixTH#1821]
https://github.com/CorsixTH/CorsixTH/blob/1f7b9b799428d3e96b8f13544d3cd9abd4466ccc/SpriteEncoder/scanner.cpp#L1501
https://github.com/CorsixTH/CorsixTH/blob/1f7b9b799428d3e96b8f13544d3cd9abd4466ccc/SpriteEncoder/scanner.cpp#L1502
https://github.com/CorsixTH/CorsixTH/blob/1f7b9b799428d3e96b8f13544d3cd9abd4466ccc/SpriteEncoder/scanner.cpp#L1513
Because 
in the functions 
https://github.com/CorsixTH/CorsixTH/blob/1f7b9b799428d3e96b8f13544d3cd9abd4466ccc/SpriteEncoder/scanner.cpp#L1499
check
`
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
        if ( ! b )
                return;
... 
`

**Comment by Alberth289346** [comment]
The file is generated by `flex` as stated at line 7. In other words, it's not manually written code.

Apparently `flex` lives at https://github.com/westes/flex/ .

If you want to fix things here, check what the current version of `flex`generates (it has been a few years since that code was generated), and if the output is still wrong, report at the above site, preferably with a patch that fixes the generated output of the program.

**Comment by lewri** [comment]
It has been 8 years I'm guessing since that code was last edited -- doesn't mean the code is bad -- but might need a look over.

**Comment by Alberth289346** [comment]
That code has never been edited, it's generated.
If you edit it, the next time you run flex, you again lost all edits, so if you need to change the code, the only useful path is to fix flex itself if there is something wrong.

Until you have a concrete test that demonstrates a crash, the only thing you have is some tool output saying "well, it might be problem." Depending on the quality of the tool that may or may not be true.

Text scanning has been around since the 70's or so, ie scanning is a solved problem. Not much to develop any more there.
So it makes sense that there are no new releases.

**Comment by lewri** [comment]
Do we particularly want to have this addressed? Whoever did set up flex years ago...

**Comment by Alberth289346** [comment]
No, at least not here.

Give the huge number of uses of this software, I would say you need to make a stronger point than just a copy/paste of some tool output. An example that actually crashes would do, although I have to see it happen before I believe it.

If there is a bug, it's in flex generated code, which means it must be fixed in its code generator. Editing generated code is pointless, as the next time it is generated, the bug is back.
