### ISSUE TITLE
[Bug] Persistence restores some integers with .0

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2038]
#### Describe the issue
Persistence has a habit or saving and changing a whole integer (e.g. 5) to a number with decimal (5.0). This isn't such an issue where the numbers aren't visual to the player.

#### Steps to Reproduce
1. Get an annual report and save game on first screen

2. Reload game and observe changes

#### Expected Behavior
Persistence should be restoring values as originally used visually.

#### System Information
**CorsixTH Version:** 0.65

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*
![image](https://user-images.githubusercontent.com/20030128/128746409-be506ca1-445e-4a21-b2fa-9baa637f62a3.png)
![image](https://user-images.githubusercontent.com/20030128/128746445-38a7259a-d24f-4ad5-83e6-2461dc981503.png)

**Comment by Alberth289346** [comment]
Earlier Luas didn't have integers (everything was float). Lua 5.3 is afaik the first Lua with integer support.

For persistence, you want to keep integers as integers and floats as floats. I think that also actually happens (otherwise you'd have major trouble loading almost all save games), so persistence is not to blame I think.

It seems that Lua 5.3 changed printing of floats:
``` sh
$ lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> c = 1 + 1.0
> print(c)
2
```
versus
``` sh
$ lua5.3
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> c = 1 + 1.0
> print(c)
2.0
```


The real culprit isn't persistence itself I think, but
- saves from older Luas aren't properly converted to integer values at appropriate places when loading into Lua 5.3, or
- printing values in Lua 5.3 is broken for integer-like floating point values.

**Comment by lewri** [comment]
Yes likely this is something out of my area or understanding.
Saying that I imagine it is fixable in some way. Though new games do it too with lua 5.4 so who knows. 

Is persistence stored in C++ or Lua?

**Comment by Alberth289346** [comment]
It's stored in a file, but performed using C++ :)

**Comment by TheCycoONE** [comment]
I can and should fix this for 5.3+ to 5.3+ but it should not have any impact on display. Where we care about the output format we need to be using string.format.

**Comment by Alberth289346** [comment]
lua5.1 accepts both `%d` and `%f` for both integers and floats:
``` lua
> print(string.format("%d", 5.5))
5
> print(string.format("%d", 5))
5
> print(string.format("%.0f", 5))
5
> print(string.format("%.0f", 5.3))
5
> print(string.format("%.0f", 5.8))
6     -- Rounds
> print(string.format("%d", 5.8))
5     -- Truncates
```
Lua 5.3 is more picky
``` lua
> print(string.format("%d", 5.5))   -- %d doesn't like floats.
stdin:1: bad argument #2 to 'format' (number has no integer representation)
stack traceback:
	[C]: in function 'string.format'
	stdin:1: in main chunk
	[C]: in ?
> print(string.format("%d", 5))
5
> print(string.format("%.0f", 5))
5
> print(string.format("%.0f", 5.3))
5
> print(string.format("%.0f", 5.8))
6   -- Rounds
```
Conclusion: Use `%.Nf` for printing values with `N` significant digits.

**Comment by lewri** [comment]
After some digging it's likely the *best* solution is probably putting it in C++, so format the number to an integer (string or not... probably string). I believe `font:draw` is probably the target in C++...

Though I'm happy to just fix this on the Lua side too... it just won't be as condensed I think.

**Comment by Alberth289346** [comment]
There are some other best solutions:
- define for each value that we have, whether it should be float or integer. Next, rigorously assert on that so it dies when it makes a mess.
- perhaps a simpler solution is to use integers everywhere, perhaps except for printing output. Again, it needs rigorously checking as Lua doesn't do that.

@TheCycoONE Could we do something with meta-tables to ensure you can assign the wrong type to an instance variable?

Note: If we move constructing text to be printed to the UI, formatting problems become limited to that area, rather than the current "all over the place". That may need expanding the language string system though, not sure.

**Comment by lewri** [comment]
In the notes of the `bank_manager.lua` I think old lua versions may scupper your first option:
```
-- Lua < 5.3 stored integer money amount in floating point values.
    -- Lua 5.3 introduced an integer representation, and started printing
    -- integer floating point numbers with a trailing .0 .
```

**Comment by TheCycoONE** [comment]
I'm not sure why we're rejecting the original proposal of solving it in the formatting strings?

**Comment by TheCycoONE** [comment]
Also font:draw has nothing to do with this...

**Comment by lewri** [comment]
> I'm not sure why we're rejecting the original proposal of solving it in the formatting strings?

I think it's just a bit ad-hoc rather than preparing some kind of proper solution, which I think is what Albert is suggesting.

**Comment by TheCycoONE** [comment]
Albert's first solution is also quite adhoc - more so than format strings. His second solution is probably untenable given how easily lua coerces numbers to floating point.
