### ISSUE TITLE
New zoom: black line clipping on certain map tiles

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2164]
Edges of the window can get black bars when zooming in. In current master.

Not present in 0.65.1

<img width="73" alt="Screen_Shot_2022-05-15_at_10 01 58_AM" src="https://user-images.githubusercontent.com/20030128/168478094-6673ade1-001c-45c8-9559-4c0066ee9ee6.png">
![unknown-6](https://user-images.githubusercontent.com/20030128/168478097-fa50345f-0f28-4f3c-98e2-1de4d05370ab.png)

**Comment by flackr** [comment]
The issue seems to be some of the clips applied from level_map::draw which are intended to clip to the screen end up being a bit short. Specifically this clip for example:

https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_map.cpp#L989

I suspect the passed in width and height must be getting `floor`ed somewhere since the scaling code in render_target::set_clip_rect always errs on the side of a larger clip to encompass / enclose the fractional clip.

https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_gfx_sdl.cpp#L646
