### ISSUE TITLE
[Bug] Crashes on Ubuntu 22.04

### ISSUE THREAD

**Issue by alperoguz** [CorsixTH/CorsixTH#2222]
### Describe the issue

Hello,

Does anyone facing this issue?

https://bugs.launchpad.net/ubuntu/+source/corsix-th/+bug/1980280

### Steps to Reproduce

It's crashing on first run.

### Expected Behaviour

.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.65.1

### Operating System

Ubuntu 22.04.1

### Theme Hospital Version

GOG.com

**Comment by tobylane** [comment]
The dependencies.txt attachment to the linked report includes lua-lpeg. Where is it installed? Is there a shortcut to it at any of the locations Corsixth listed?

LUA_CPATH can be extended to include lpeg's location, in the same way as PATH.

**Comment by lewri** [comment]
This one might be upstream (I think I remember a report like this a while back somewhere...) rather than a direct fault of ours. Will need someone to verify.

**Comment by lewri** [comment]
Just to add, I can replicate on my VM on launch (if installed direct from apt)

![image](https://user-images.githubusercontent.com/20030128/186995397-f1816fab-b06f-41df-90e6-856407d7b094.png)

**Comment by Alberth289346** [comment]
apt also has `lua-lpeg` (at least in my ubuntu 20 derivative system), maybe try to install that as well and see what happens then?

**Comment by lewri** [comment]
@emorrp1 has posted this was fixed in lua-lpeg . But you may need to download their new version manually (if that's how I understood it)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014563#10

**Comment by lewri** [comment]
@alperoguz so moving forward it looks like we generally recommend using the flatpak version for linux users.
https://flathub.org/apps/details/com.corsixth.corsixth
Using the flatpak means that all dependencies are handled and the installation is kept up to date with our new releases.

However, while it looks like the `lua-lpeg` update was put to *buntu 22.04 it went to active development instead of stable.
You can workaround this by going to the launchpad page for `lua-lpeg`, downloading the relevant `.deb` for your architecture and installing it with `sudo dpkg -i yourpackagehere.deb`

E.g. a 64-bit intel/amd system would use `lua-lpeg_1.0.2-2_amd64.deb` from that page.

**Comment by lewri** [comment]
Closing as resolved in lua-lpeg 1.0.2-2.

**Comment by lewri** [comment]
FWIW, 0.66 is now being backported to *buntu 23.04
