### ISSUE TITLE
[Bug] Occasionally the game gives too hard an emergency 

### ISSUE THREAD

**Issue by MRMIdAS** [CorsixTH/CorsixTH#2255]
### Describe the issue

Playing on Level 7 of the campaign, gave me a 10 person Unexpected swelling emergency, where normally Surgery emergencies are considered "Hard" at 4 or 5 people.

### Steps to Reproduce

1. Load Level 7

2. Play a while

### Expected Behaviour

less people for that kind of emergency overall, given the room type.

### CorsixTH Version

0.66

### Operating System

Win10

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
In Level 7, the first emergency is Unexpected Swelling. However, the level file says Min patients 1; and Max patients is 1. So why you ended up with 10 I'm not sure.

**Comment by MRMIdAS** [comment]
Definitely wasn't the first emergency, was a couple of years in at least, I'd had a large Pharmacy emergency before this one, and a couple of contagious diseases too, if that makes any difference.

**Comment by lewri** [comment]
Sorry, I read the level file wrong (the numbers used for diseases can get confusing).

A months 26-30, Unexpected swelling emergency can occur. Min patients 8, max 10 ,in hard and medium difficulty. In easy it is 7 - 9.

My thought is that, being 2.5 years in the game expects you would have made a second operating theatre (or had the capacity to make one at short notice). So technically this is an original game issue (rather than ours).

Also that in the original TH, I'm pretty sure emergencies were harder -- as the timers were shorter than in CorsixTH.

**Comment by lewri** [comment]
Just to add on, the pass threshold for this emergency is 75%, so the game doesn't hold it against you not to cure everyone in time (how nice)

**Comment by MRMIdAS** [comment]
Fair enough, seemed a bit harsh to me, especially with how other OT emergencies are, even in the latter half of the game. I needed 3 OT's to handle this emergency, and just didn't recall that in the original TH.
