### ISSUE TITLE
Drug improvements seem to be slow

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#230]
@Lego3 I know this has been mentioned before and I know we did a lot of research on this at the time, but even so drug improvements do seem to be a lot slower than they were in TH.
As an example I can have a large research room with four to six desks and only hire consultant researchers and the drug improvements take 4 - 5 years to get from 80% to 100% and that is with drug improvements taking most of the 100% you have to play with in the research screen.
Having looked into the code I see that there is something called gbv.ResearchPointsDivisor which does not exist in the original level files, but does in the base config and in research there is and "or 5".  So all the research points are being divided by this number.  In my custom game I reduced this to 3 in the hopes that this would speed up research, but it didn't - not noticeably anyway.  In my custom map I am half way through the fourth year and I still have five drugs at 95% and the starting point was 85%, this is with four consultant researchers and research on drugs at 85% for most of that time.  Research on actual machines seems to be quite fast by comparison even though that research percentage is low.  I don't know what the purpose of gbv.ResearchPointsDivisor was for and whether it is that that is slowing things down.  If you do get any spare time, would you be able to take a look to make sure there is not something that is making drug improvements slower please?

**Comment by mugmuggy** [comment]
Pulling out an old issue, as I've been digging into TH a bit and can see somethings that could be addressed here and not sure if it is still an issue but we can have the discussion here.

Drug research - I've found that the original game, would randomly improve an aspect - effectiveness or cost, rather than alternate between the two. So you might improve effectiveness faster than cost more often. The original game also has a 1/7 chance that you also improve the other aspect at the same time. Original reduces the cost in 5% steps (of the current cost) - Corsix has this fixed at $10 (about 10% in earlier levels) - so Corsix tends to lower cost greater and potentially faster. In original the price for drugs varies between drugs because of the more random nature and Corsix looks like all drugs are researched and cost the same. From an early look at it, I haven't checked how long if at all a drug is cost improved after reaching 100% effectiveness.

As for machine improvements, it does alternate between improvements. Original though, from my analysis so far, 1/3rds of the time, there is no improvement at all, and it improves strength over cost. It appears it stops improving machines after 6 cycles of nothing/strength/cost improvements, but I need to verify that.

Though I don't believe there are any issues with the normal game levels, drug cost in corsix could go negative, original has a minimum of $10, machine cost calculations look correct, except they also have a minimum of 1/3 the original cost in the original

**Comment by lewri** [comment]
Been a few years this issue went cold but I would support aligning more with original as per mugmuggy's comments.
