### ISSUE TITLE
[Bug] Cannot edit items in corridors

### ISSUE THREAD

**Issue by bennuttall** [CorsixTH/CorsixTH#2317]
### Describe the issue

In the original game, you could use the "Edit rooms/items" button to pick up and move (or remove) items placed in corridors (i.e. outside of rooms), but that isn't possible in corsixth. Clicking the button changes the cursor to the scissors as expected, and although this allows selecting a room to edit, it doesn't allow selecting an item, for example a bench or vending machine.

This is especially annoying when you create a room, place benches up against its walls, and later wish to remove the room and benches, or replace the room with a larger one and move the benches with it. Or simply if you place a bench in the wrong square by accident.

### Steps to Reproduce

1. Start a new game

2. Place a bench

3. Click the Edit rooms/items button

4. Try to click on the bench

5. Observe inability to make the selection

### Expected Behaviour

It should be possible, as it is in the original game, to select items such as benches, and move or remove them.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.66

### Operating System

Ubuntu

### Theme Hospital Version

GOG.com

### Additional Information

Trying to select the bench with scissors:

![Screenshot from 2023-04-17 21-09-27](https://user-images.githubusercontent.com/1609725/232599269-0ab3ea2f-fc36-4654-8620-54ba98702ea1.png)

If you try to select a bench next to a room, you sometimes catch focus on the corner square of the room by mistake:

![Screenshot from 2023-04-17 21-09-44](https://user-images.githubusercontent.com/1609725/232599283-434b67ea-eee5-4e8d-8b33-43a5ca0acac8.png)

**Comment by lewri** [comment]
Greetings!
As far as I'm aware, it's right click to move an object in the corridor. I've never known the scissor cursor to do this myself.

**Comment by bennuttall** [comment]
Wow! That's good to know - thanks!

I'm fairly sure the original game allowed using the scissor tool - but glad to know there's an easier alternative.

**Comment by ARGAMX** [comment]
I'd like to be able to move objects in the hallway using scissors.

Because CorsixTH doesn't highlight the item the scissors are pointing at, and because the cursor selection is handled in a very strange way, you sometimes select the wrong item, and you can't see what will be selected in advance.

It's precisely because of these circumstances that you can select a room instead of an item, thus evacuating humanoids from the room. I agree with this problem.

But I believe this evacuation issue is a consequence of the lack of highlighting and an incorrect selection algorithm.
And not because the scissors themselves are bad.

I used scissors constantly in Theme Hospital and understand the author. It's a useful tool.
When there aren't many objects piled up nearby, right-clicking is better and faster. 
But when there are a lot of items piled up nearby and the cost of error is high, scissors are much better and safer.
Using the `V` hokey in CorsixTH you can quickly turn this mode on/off.

In fact, the lack of scissor-based pickup functionality, like in the original game, prompted me to implement Cancel accidentally grabbed object #3304.

In CorsixTH, in densely packed hospitals, you constantly miss right-clicking. 
Bacause you simply don't have a precision selection tool. 
Every time you right-click to select something in the hallway, you just pray, to grab what you wanted and not something else.

I think we could implement this scissor behavior in CorsixTH. It's quite useful. And besides, it won't cause any harm to those who don't need it.

I initially wanted to open a similar issue myself, but it turned out someone had already made a similar request when I found this thread.
