### ISSUE TITLE
Just info really please and thank you.

I've downloaded it from the corsix TH website not this github page and just added my rom to it, it's version 0.50

Is there an updated android port tgat would supportHD? But I'm happy just to be able to play it on the go...

YOU GUYS HAVE DONE AN AMAZING JOB! 

### ISSUE THREAD

**Issue by bouncingbenji** [CorsixTH/CorsixTH#2336]

**Comment by Alberth289346** [comment]
You have the newest Android version.

The Android project is not maintained currently.

See also the Getting Started wiki page:
https://github.com/CorsixTH/CorsixTH/wiki/Getting-Started

In "The long version" section, in "1. Operating system", it says "Android - No longer maintained" there is a non-working link there so that is not likely to give new information.
