### ISSUE TITLE
[Bug] Direct Zoom shows black dots

### ISSUE THREAD

**Issue by ageekhere** [CorsixTH/CorsixTH#2403]
### Describe the issue

Black dots can sometimes show.
![Screenshot 2023-09-17 195944](https://github.com/CorsixTH/CorsixTH/assets/13173133/02709d63-8e72-4a43-9ecf-0305c9d8dd4b)

### Steps to Reproduce

1. Move the camera around and they can show up.

### Expected Behaviour

no black dots 

### Save Game

Save game attached to report: No

### CorsixTH Version

0.67

### Operating System

Windows 11

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
That's direct zoom related I think. You can turn it off in the config.txt file and set it to false. It should then go away.

I've seen a few sporadic reports of this now, did we want to try improving it in direct zoom?

**Comment by Squall-Leonhart** [comment]
This should be retested against master, it may have had the same origin as the Nvidia tiling artifacts.

**Comment by lewri** [comment]
I can still replicate this -- though again I'm on AMD so it may be these artifacts are less noticeable on that card. Will get an NVIDIA platform tested when I can.

**Comment by ageekhere** [comment]
using version 0.67 and nVidia graphics driver 551.76 i still get the issue
![Screenshot 2024-03-11 080213](https://github.com/CorsixTH/CorsixTH/assets/13173133/915d1e8e-dc18-4fc7-b564-fb1b0db2f49c)

**Comment by lewri** [comment]
> using version 0.67 and nVidia graphics driver 551.76 i still get the issue ![Screenshot 2024-03-11 080213](https://private-user-images.githubusercontent.com/13173133/311544138-915d1e8e-dc18-4fc7-b564-fb1b0db2f49c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDY2NTMsIm5iZiI6MTcxMDEwNjM1MywicGF0aCI6Ii8xMzE3MzEzMy8zMTE1NDQxMzgtOTE1ZDFlOGUtZGMxOC00ZmM3LWI1NjQtZmIxYjBkYjJmNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDIxMzIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYzk1NjIyN2VjNTk5NzUxMDQ0NDMxNDYwYjlmY2FkYTU5Y2ZjYWFkOTZlNzQ4MjE4NDYzZTQzZDQzN2UyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQLvYuzPB74qqDCzCxJJxkuXFjZ8tNrBgPYWTGxL0Rk)
0.67 won't get any of the upcoming fixes as a release until later this year.

Could you try the artifact here if you get a chance (it's our latest continuous integration build) in the new few weeks and let us know if they still appear in it? https://ci.appveyor.com/project/TheCycoONE/corsixth/builds/49365550/artifacts

Just download the zip and unzip it anywhere in an empty folder on your computer (preferably not over your existing CorsixTH install). Then run the exe.

**Comment by ageekhere** [comment]
![Screenshot 2024-03-11 093331](https://github.com/CorsixTH/CorsixTH/assets/13173133/9121e23f-5d0c-45d5-8548-1263c12421d7)
Just tested and it is still there

**Comment by Squall-Leonhart** [comment]
There's a timing issue afoot, without the intermediate texture theres no delay on the scaled texture copy so its presenting while the zoom on a previous frame is being processed.

A triple buffering approach would mitigate this, but the expense would be an extra frame of latency, otherwise synchronising to the completion of the previous zoomed frame would do it too, at the expense of some performance on weaker processors.

**Comment by lewri** [comment]
We'd probably need @flackr to advise. But he's quite a busy guy. It probably would be better to support an approach that does not have any significant impact on performance.

For now, if the issue is a problem to the user we advise disabling direct zoom. Direct zoom also has some impact on blueprint textures noted in https://github.com/CorsixTH/CorsixTH/discussions/2218#discussioncomment-3450305

Of course, this is free to be picked up by someone else if they're interested in providing a fix for it.

**Comment by flackr** [comment]
In my local testing, simply increasing the scaling overdraw amount a little closed up all visible pixel gaps when smoothly zooming in/out. I've sent a PR with this change.

**Comment by lewri** [comment]
@ageekhere can you try the artifact now at https://github.com/CorsixTH/CorsixTH/actions/runs/8681854515 (should be up for a few days) and if it things are okay now (another Windows Portable version you just unzip into a folder and run).
