### ISSUE TITLE
[Bug] Game crash while building a ward

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#2476]
### Describe the issue

First level, build large ward, after placing door and no windows, game sometimes crashes on going to the next phase

![Screenshot from 2024-01-26 21-28-53](https://github.com/CorsixTH/CorsixTH/assets/3254232/1a81e1db-b5de-42e1-b6a1-10ec2994a4ee)

Crash stackdump in the gamelog part of the issue

### Steps to Reproduce

1. Start new level in master 835bb9aa

2.  Select ward room to build, drag a rectangle, place a door (not close to either side may be significant, not sure)

3. Skip placing windows by pressing on 🗸 for the next phase

4. Crash (sometimes), not sure if trying again will ever crash if the first time didn't. I never tried that much though.

### Expected Behaviour

Sane looking walls and door, and being able to place a bed :)

### Save Game

Save game attached to report: No

### CorsixTH Version

master 835bb9aa

### Operating System

Mint - something

### Theme Hospital Version

CD

### Gamelog.txt

```bash
starting game with difficulty full
Created game with savegame version 181.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
...rth_fork/CorsixTH/Lua/objects/doors/swing_door_right.lua:44: attempt to index a nil value (field 'slave')
stack traceback:
	...rth_fork/CorsixTH/Lua/objects/doors/swing_door_right.lua:44: in local 'constructor'
	...dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/class.lua:74: in field '?'
	...dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/world.lua:1973: in method 'newObject'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:489: in method 'finishRoom'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:230: in method 'confirm'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:342: in method 'clearArea'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:226: in local 'callback'
	...ev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/window.lua:699: in method 'handleClick'
	...ev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/window.lua:1658: in field 'onMouseUp'
	...rsix_alberth_fork/CorsixTH/Lua/dialogs/place_objects.lua:452: in function <...rsix_alberth_fork/CorsixTH/Lua/dialogs/place_objects.lua:451>
	(...tail calls...)
	...ev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/window.lua:1642: in field 'onMouseUp'
	...th/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/ui.lua:877: in function <...th/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/ui.lua:864>
	(...tail calls...)
	...h/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/app.lua:1102: in function <...h/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/app.lua:1097>
```

### Additional Information

App has version line
``` lua
local SAVEGAME_VERSION = 181 -- Pair swing doors instantly
```

Previous MR: https://github.com/CorsixTH/CorsixTH/pull/2436

Previous BR: https://github.com/CorsixTH/CorsixTH/issues/2389

**Comment by lewri** [comment]
Problem exists because of this `repeat` loop (encased in a `pairs` loop) that can lead to an event where the `slave` door is made before `master`
https://github.com/CorsixTH/CorsixTH/blob/835bb9aad6d751749ff88e9449797547bf6424da/CorsixTH/Lua/dialogs/edit_room.lua#L451-L499

The PR #2436 made this issue exposed. In `entrance_door_right` @corsix planned for this with a handler for reacting to whichever order the door halves were created.
https://github.com/CorsixTH/CorsixTH/blob/835bb9aad6d751749ff88e9449797547bf6424da/CorsixTH/Lua/objects/doors/entrance_right_door.lua#L44-L59

Resolution options as worked out:
1. Revert the instant pair code, make any potential interactions to slave be ignored until they pair with the master (e.g. #2389)
2. Implement Corsix's method for entrance doors on swing doors (maybe add a handler for when `slave` isn't paired for interaction issues)
3. Rewrite the `finishRoom` code (or some other handler) to ensure master door is built first
4. Rewrite the code to merge the `master` and `slave` door build code in one branch.

**Comment by lewri** [comment]
From the sense of following what we already do for Entrance Doors, 2 is in my opinion the most reasonable solution right now.
However, because the swing door talks to other code, it definitely needs a cover period for that minute window of potentially not being paired.

**Comment by Alberth289346** [comment]
I agree 2 looks like a reasonable solution.
