### ISSUE TITLE
gh-pages - Update on release not working

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2609]
The update website action when we publish a release has been broken since 0.67.
Originally I thought it was just me, but it's also happened to @TheCycoONE (not sure if @rmnvgr has had it too).

I can push a manual refresh  via my blog if necessary, but I'm guessing this one should be fixable?

Error in actions just givens: Invalid credentials/bad token.
https://github.com/CorsixTH/CorsixTH/actions/runs/10711524484/workflow

**Comment by rmnvgr** [comment]
Looks like the access token is wrong? I don't have access to the site's tokens nor this repo's secrets, but since it's still working for the blog, I'd guess the issue is with the `WEBSITE_REPO_TOKEN` secret on this repo. Or maybe two access tokens were created on the website's repo and the one for the dispatch action expired?

**Comment by rmnvgr** [comment]
Yes I manually ran the action to make it appear.

**Comment by TheCycoONE** [comment]
Ok, I'll sort it out, thanks @rmnvgr

**Comment by TheCycoONE** [comment]
We are hopefully good now until October.
