### ISSUE TITLE
[Bug] 'free_build_mode' param affecting campaign maps.

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2627]
### Describe the issue

'free_build_mode' apply to any of the campaign maps. But it should not.

'config.txt' says, that 'free_build_mode' does not apply to any of the campaign maps.

<img width="531" alt="Screenshot 2024-09-21 at 22 47 53" src="https://github.com/user-attachments/assets/f8e67d3c-5640-4e7f-a07d-7e78bc401da0">

Also it looks very strange for me that enabling option 'Free Build' on 'Single Scenario' menu affecting anything outside of that screen. As keeping 'free_build_mode' in 'config.txt' too.
It seems more reasonable to me to select this value only at level start and not keeping it in game configs. So it can only affect this Single Scenario start.
Or maybe there is some meaning to keep 'free_build_mode' in 'config.txt' which I don't understand?

### Steps to Reproduce

1. Run game. 
2. In Main Menu select 'Single Scenario'.
3. Enable option 'Free Build'.
4. Press 'Back' to back to main menu.
5. In Main Menu select 'Custom Campaign'.
6. Select any campaign, press 'Start'.
7. Observe that you have $0 at the start and you in 'Free Build' mode.

### Expected Behaviour

1. 'free_build_mode' should not apply to any of the campaign maps.

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment]
Config implies it's a permanent setting. But the UI would indicate it's game specific.

But also, it's affecting campaigns even when it says it doesn't? It certainly would stop you progressing a campaign. Will look but I think `world` currently sets free build during setup of a game.

**Comment by Matroftt** [comment]
app.config.free_build_mode - this is a variable which is enabling free build, it should be set as false on a new campaign game

**Comment by Matroftt** [comment]
```lua
function UICustomCampaign:buttonStartCampaign()
  if self.chosen_item then
    self.ui.app.config.free_build_mode = false
    TheApp:loadCampaign(self.chosen_item.path)
  end
end
 ```
Would this fix be fine or no?

**Comment by lewri** [comment]
The world stores the free build choice so it would be better to implement with the existing code there.
https://github.com/CorsixTH/CorsixTH/blob/afcc4c2f22587091d5651e257d830eb6f8a061dd/CorsixTH/Lua/world.lua#L83-L88

However, there is another problem. The world doesn't know this is a custom campaign at the time free build is set, because it isn't passed the data until later.
https://github.com/CorsixTH/CorsixTH/blob/afcc4c2f22587091d5651e257d830eb6f8a061dd/CorsixTH/Lua/app.lua#L604-L608

Trying to manipulate a config value on the fly is usually a bad idea, especially because if you for some reason later in the program trigger a `saveConfig` call, free build's config value will be changed.

A few options:
1. Rework when free build is set in a game
2. Move the free build decisions elsewhere (but probably still retain the actual final value in world)
3. Remove free build as a `config.txt` option, by default assume it is false, and have it set as and when through 'Custom Game' instead per-game (aligns a bit with the point @ARGAMX has made).
