### ISSUE TITLE
[Bug] Spamming grab of occupied employe causes unexpected behaviour.

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2632]
### Describe the issue

Spamming grab of occupied employe causes unexpected behaviour.

For example, after promotion to Consultant while standing up from desk on Doctor details-view press grab button several times causes bugs.

<img width="378" alt="Screenshot 2024-09-24 at 22 09 17" src="https://github.com/user-attachments/assets/5de27218-fd2c-4c55-831d-07ad9883d405">

Load '**after**' save and observe how H. WRIGHTLET (Training room) and G. WARBURY (Research room) unexpectedly and for no reason leaving they rooms. 'staff leave rooms setting' is disabled. There is no any calls.

This is the consequence of Spamming grab of occupied employe.

### Steps to Reproduce

Characters:
7 H. WRIGHTLET - **Lector**
21 G. WARBURY - **Researcher**

1. *Load '**before**' save game attached to this ticket* 
2. Observe how **Lector** is teaching **Researcher** in Training room.
3. Soon **Researcher** becoms Consultant.
4. At the speed 1 while **Researcher** standing up from desk, open **Researcher**  Doctor details-view.
5. Press Grab button several times. (if press 1 time then bug not reproduce)
6. **Researcher** will not be grabbed instantly. There some delay as he occupied. Wait until he will finish standing up from desk.
7. Put **Researcher** in Research room.
8. Observe that 'Multiple grabbing bug' happen - you put **Researcher** but he had got grabbed again. Put him in another place in Research room.
9. Set game speed to 4 and Observe how **Lector** unexpectedly and for no reason leaving Training room and **Researcher** unexpectedly and for no reason leaving Research room. 

### Expected Behaviour

1. Spamming grab of occupied employe should not be possible.
2. Doctors should not leaves they rooms unexpectedly and for no reason.

### Save Game

[researcher_leaves_room_unexpectedly_after.sav.zip](https://github.com/user-attachments/files/17119491/researcher_leaves_room_unexpectedly_after.sav.zip)

[researcher_leaves_room_unexpectedly_before.sav.zip](https://github.com/user-attachments/files/17119694/researcher_leaves_room_unexpectedly_before.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment]
For expected behaviour point 2 the Training room one is expected. You became a consultant and have finished learning what you can, you are not there to teach the room so you must leave. 

This issue seems a little confused to the first impression I got, which was that staff were leaving any room if they became a consultant. 

Actually what is really meant here is they spamming grab causes unexpected behaviour.
In CorsixTH when you grab, the humanoid must finish their action to an interruptible state. This causes a delay in the grab and is required currently to prevent other bugs. In the original, a grab just stopped the action regardless of position. The most notable occurrence between the two games is in the operating theatre, which during the surgery usage cycle there is a long time before the surgeon can be grabbed proper.

So a solution here is potentially to ignore additional grab actions on a humanoid already grabbed once. We could potentially also use the zzz cursor for this.

It could also be scenario specific -- you interrupted a leave action that could have a `must_happen` flag and the action hasn't been told it's safe to drop.

**Comment by ARGAMX** [comment]
Also about Spamming grab:

If doctor occupied you can't take him instantly, but you can dismiss him anytime. Even during operation. So if you try to take occupied doctor and also press dismiss button, after while fired doctor will be grabbed and you will be able to place him at any place in your hospital. So you can go further and place him in blocked area (Allow Blocked Areas). 
Sometimes I collect these fired employees who was working not good enough in one of the hospital toilets.

<img width="170" alt="Screenshot 2024-09-25 at 10 35 36" src="https://github.com/user-attachments/assets/1ed9b094-f8e8-46aa-bdf8-601112a9fd8b">

Sometimes it so fun so that I'm no longer sure whether it's a feature or a bug. 😂

**Comment by lewri** [comment]
Are you trying to grab after firing them in that scenario above?

**Comment by ARGAMX** [comment]
> Are you trying to grab after firing them in that scenario above?

No. I am trying to grab humanoid while they occupied. But no any actual grab happening. So I dismiss (fire from hospital) humanoid. After humanoid finish his action and moved to an interruptible state, then actual grab happening. And I can place fired humanoid anywhere in Hospital.
