### ISSUE TITLE
[Bug] Pause screen overlay missing

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2734]
### Describe the issue

When you press P and pause enabled there is no corresponding screen overlay.

vanilla TH:

<img width="456" alt="Screenshot 2024-12-08 at 18 20 37" src="https://github.com/user-attachments/assets/6d493f1c-5aa3-4f1c-9032-9dc7d0f269a6">

CorsixTH 0.68.0:
check 0:27 and 0:32

https://youtu.be/8zXQyL75ysI

### Steps to Reproduce

1. Start new Single Scenario or Campaign.
2. Press P.
3. Observe that Pause is enabled and pause screen overlay missing.

### Expected Behaviour

Pause screen overlay should be as in vanilla TH.

### CorsixTH Version

0.68.0, 0.67.0, 0.66.0

### Operating System

MacOS Sonoma 14.5

### Theme Hospital Version

GOG.com

**Comment by MandrakeHorse** [comment]
CorsixTH already has this feature.

- If Build While Paused is set to On, a blue overlay will cover the screen (see below screenshot), preventing the user from interacting with their hospital or opening any menus. This mimics the behaviour of Theme Hospital, with the exception that music will continue to play and the user will be able to scroll the hospital.
- If Build While Paused is set to Off, this overlay won't appear so that the user can interact with their hospital and the menus while paused.

![2024-12-08 16_31_13-Greenshot](https://github.com/user-attachments/assets/7e54d75e-a9ed-48a1-8094-9d87c5544ba9)

**Comment by ARGAMX** [comment]
> CorsixTH already has this feature.

Thanks [MandrakeHorse](https://github.com/MandrakeHorse). 
Didn't know about that.
That make sense.
