### ISSUE TITLE
Music rearranged mp3 files

### ISSUE THREAD

**Issue by excpt** [CorsixTH/CorsixTH#282]
Hi, 

I took a look at the original midi files and setup new instrument arrangements.You can download the mp3 files.

Feel free to comment, criticise and rate the tracks.

Track list:
- Atlantis: https://soundcloud.com/timrudat/the-hospital-atlantis
- Fortune: https://soundcloud.com/timrudat/theme-hospital-fortune
- Candy: https://soundcloud.com/timrudat/theme-hospital-candy
- Doctor: https://soundcloud.com/timrudat/theme-hospital-doctor
- Mend: https://soundcloud.com/timrudat/theme-hospital-mend
- Nightsh: https://soundcloud.com/timrudat/theme-hospital-nightsh
- Sixseven: https://soundcloud.com/timrudat/theme-hospital-sixseven
- Steady: https://soundcloud.com/timrudat/theme-hospital-steady

**Comment by xcom169** [comment]
Is it possible to add additional 3rd party MIDI music files to the game?

**Comment by ryan-edgewurth** [comment]
> Is it possible to add additional 3rd party MIDI music files to the game?

As in like, custom MIDI data or custom MP3s.

Custom MP3s is completely possible, however MIDIs are sort-of achievable. In order to add it, you'd need to convert it (on Windows either through DOSBOX and the converter in the midi data root (e.g.
`C:\HOSPITAL\SOUND\MIDI\`), or using MidiPlex.

If it is requested enough, I could write a wiki article on how to insert MIDI Music into Theme Hospital and CorsixTH.
