### ISSUE TITLE
Counting dates in CorsixTH

### ISSUE THREAD

**Issue by sadger** [CorsixTH/CorsixTH#43]
Currently world.lua and possibly other files track the date in months (this stems from the original level files operating in months) meaning all over the code base there is explicit conversion of date in months to the actual month something like `actual_months = 1 + ((months - 1) mod 12)` i.e. 
- months = 12 = actual_months = 12 and
- months = 32 = actual_months = 8 (August of year 2) 

Ideas for solving this would be one of:
1. Track the actual_months separately either keep them updated or introduce functions to calculate them on the fly `get_actual_months(months)` 
2. Rework how counting is done either count years and month separately so
we always have the actual month, or just count in months and work out what 
year it is when required (currently knowing the year isn't a very common operation but a necessary one) 

The second way is my preferred way but this is really an open discussion.

**Comment by Alberth289346** [comment]
The issue seems a little bigger than months.

There are also 'day' and 'hour' variables. Lots of code seems to be checking for a point in time by comparing day and month variables, or setting up future points in time by adding amounts to days or hours. In case of the former one then has to check for end-of-month cases, etc (earth quakes).

A direction for this issue could be to have a central notion world.current_time measured in hours since game-start, and relate all timing and timers to that notion.

The simplest form of that time notion would be a single integer, but I can also imagine a table or class with several fields. A table or class would allow keeping shadow variables like month_in_year, etc for reducing cpu costs in converting.

It should be possible to create future points in time, and check whether points in time have already passed (a fundamental question here is how to handle different time granularities, eg how many hours is 'two days from now', if the current hour is 5 (with 50 hours in a day)).

Finally, one should be able to get human-readable dates from it, for display.
