### ISSUE TITLE
New suggestion: "there must be a doctor in this room"

### ISSUE THREAD

**Issue by Glimmer-Man** [CorsixTH/CorsixTH#442]
Suggestion for new function: new button "there must be a doctor in this room". This function will make doctors go to any free room, after they leave staff room. Even if that room will have empty queue.

**Comment by lewri** [comment]
I'll update with my thoughts. I'm not averse to this suggestion but I believe since this there have been other options discussed to alleviate knock on issues (staff not responding to room calls far away etc). However, it is definitely not something original of the game scope.
This could be a level of micromanagement we don't want to go down for CTH. And you'll need to keep track of your 'must occupy' rooms by clicking on every one.

**Comment by Alberth289346** [comment]
I don't understand the "why" behind the suggestion. That is, given the answer is "add a button", what was the problem?

As TH is about micro management, I am not against it, but the suggestion looks to me as an aim at less micro-management rather than more.

**Comment by lewri** [comment]
No real appetite was given fro this.
