### ISSUE TITLE
Graphical: couch floats over doctor

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#463]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on February 08, 2011 14:35:41_

Not sure what caused this, the Dr is under the couch!

**Attachment:** [screen.PNG](http://code.google.com/p/corsix-th/issues/detail?id=735)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=735_

**Comment by TheCycoONE** [comment]
Does anyone have a save for this issue?

I'm looking to address problems like this now

**Comment by MandrakeHorse** [comment]
To reproduce the issue, the patient's couch must be orientated so that it stretches from north-west to south-west. If the psychiatrist stands in front of the upper-half of the couch, he will appear underneath the couch.

Save file - 
[issue463_CorsixTHsave.zip](https://github.com/CorsixTH/CorsixTH/files/12708579/issue463_CorsixTHsave.zip)

Screenshot - 
![2023-09-23 23_45_32-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/e0819b8d-980d-4cdd-af95-fab145019da5)

**Comment by lewri** [comment]
Merged into meta
