### ISSUE TITLE
Graphic glitch while using the cardiogram

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#472]
_From [Alberth2...@gmail.com](https://code.google.com/u/117559702027655025914/) on July 24, 2011 14:44:37_

When placing the cardiogram machine against the left wall, a graphic glitch occurs while using the cardiogram, see the picture.

The outerwall is partly missing :O

Using revision r1352 .

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=946_

**Comment by MandrakeHorse** [comment]
To reproduce this issue, the treadmill must be orientated so that patient runs towards the north-west and placed directly against the south-west wall. When the patient uses the treadmill, the left edge of the trolley will overlap with the wall.
![2023-09-30 01_11_02-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/5512c65e-8d10-45db-aede-11cb36e8f1ed)

**Comment by lewri** [comment]
Merged into meta
