### ISSUE TITLE
Possible to treat emergency illness that you have not discovered!

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#506]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on November 13, 2012 15:39:42_

I don't know whether this should be possible or not, I suspect not.
I received a fax for several patients with invis' and it said I could treat them.  I have not yet discovered invis, but most were treated.  After the emergency was over I had an invis' go to the GP and invis' was then discovered.
You can see from the pic that invis' is not in the casebook yet.

Win7 using directx testing 0.11RC with level 6 and the emergency was in Nov of the first year

**Attachment:** [3a.png](http://code.google.com/p/corsix-th/issues/detail?id=1384)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1384_

**Comment by TheCycoONE** [comment]
I still think the most sensible option is to automatically decline an emergency if you can't handle it - just like in real life - it would go to one of your competitors instead.

**Comment by MarkL1961** [comment]
You can handle it though, it is treatable just not discovered.  There are plenty of diseases in the game which are treatable before they are discovered, although this could be poorly thought out sam files.
The error only occurs if you try an view the disease in the casebook as described in the connected issue.  Otherwise they are treated and leave like anyone else.

**Comment by TheCycoONE** [comment]
Emergencies are essentially rewards for having a well managed hospital (as opposed to earthquakes and epidemics which are punitive). In that sense it makes sense to reward research as well as having lots of doctors and rooms.

**Comment by MarkL1961** [comment]
I have researched the treatment.  Emergencies are already diagnosed, they require treatment only.
Just because TH would skip them when you have not discovered the disease could be a bug.
If I could not treat the emergency it will still be offered to me, it would be a mistake to accept it though.
I can treat it, so I accept it.

**Comment by Alberth289346** [comment]
Documenting suggested fix:

After accepting the emergency, it is assumed that details of the disease are messaged along with the patient details, leading to discovery of the disease.
Conceptually, this is equal to a doctor discovering the disease in a GP, which is performed by the
```` lua
self.hospital.research:discoverDisease(patient.disease)
````
call at line 147 of gp.lua.

After accepting the emergency fax, the code should check whether the disease is known, and if not, perform the above call.
