### ISSUE TITLE
Earthquake Toggle in Level file 

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#559]
_From [Wolfwood...@aol.com](https://code.google.com/u/116646578876211261859/) on June 22, 2013 02:12:57_

it would be helpful if there was a way to set on/off earthquakes inside the .level file. As is there seems to be no way to disable it like in earlier levels of the Theme Hospital Campaign. 

It's very annoying sometimes due to how it effects buildings, and currently seems to lack a reaction period before larger earthquakes, making it hard to stop particularly bad ones.

If there was a way to just turn it off, it would be great for levels where you just want to build for the sake of building.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1653_

**Comment by sadger** [comment]
This is fixed with commit 7f7fffa90106098. Changing severity to 0 in the level file will disable earthquakes.

**Comment by MarkL1961** [comment]
Is it?!

**Comment by sadger** [comment]
I assumed that code fixed it but if it's not the case i'll reopen this then.

**Comment by MarkL1961** [comment]
I think that one possible solution would be to have a config option that turns off random earthquakes.  That way the extra code for the campaign could be removed and setting severity to 0 would then work if the player had also turned off random earthquakes.  This way, if a player wanted to add earthquakes into the early campaign levels they could do.
The code for random earthquakes it written to add them once the planned ones on the level file have finished, which is why I think at the moment they kick in when severity is 0.

**Comment by TheCycoONE** [comment]
When we investigated this, didn't we find that the original game didn't do random earthquakes at the end of the specified ones.  If so, I consider that may be the best fix.

**Comment by TheCycoONE** [comment]
Closing as a duplicate of #296

**Comment by fusionstream** [comment]
Setting #quake_control[0].StartMonth.EndMonth.Severity 0 0 0 still produces random high severity earthquakes with no pre-tremors... This was present since 0.40 (iirc).

**Comment by fusionstream** [comment]
Sorry, forgot to mention that now I'm posting for 0.60

**Comment by MarkL1961** [comment]
I think since 0.60 this has been improved upon.  I have been testing the trunk version for  a few weeks and we now get a tremor followed by the main quake - damage has been less severe as well

**Comment by TheCycoONE** [comment]
My earthquake rewrite was done after 0.60 and will be in the next release.
