### ISSUE TITLE
Configuring CMake In Windows: Auto Find Library Paths

### ISSUE THREAD

**Issue by J-Shep** [CorsixTH/CorsixTH#609]
Instead of having to give the Windows CMake GUI program every required library path a CorsixTH developer could just give it a path to a libraries directory on their computer where they could store all of CorsxTH's required libraries. CMake could then automatically find all the required library paths.

**Comment by J-Shep** [comment]
No cmake file changes will be required, I think a Windows developer just needs to use these two Cmake environment variables with the path to their libraries directory:
* CMAKE_INCLUDE_PATH
* CMAKE_LIBRARY_PATH

**Comment by J-Shep** [comment]
>> No cmake file changes will be required, I think a Windows developer just needs to use these two Cmake environment variables with the path to their libraries directory:

The paths provided have to be to the directories which contain the include/library files, but you can use * in the paths to mean "any directory name", so a include path could be:
>> C:\Users\<Name>\Documents\Github\Libraries\*\include"

This would work as long as there's only one directory before the include directory.

**Comment by J-Shep** [comment]
>> ... but you can use * in the paths to mean "any directory name", so a include path could be: ...

I was wrong: 
>> .../Libraries/*/include 

Is not valid.

**Comment by TheCycoONE** [comment]
In linux all include headers would be in one folder, similarly all libraries would be in .e.g. /usr/lib.  I don't think there's anything stopping you from doing the same thing in Windows which would make the CMAKE_INCLUDE_PATH etc. work, but it's a little hard to manage updates without a package manager to take care of what package owns what files.

On my system I actually have x86_CacheInit.txt and x64_CacheInit.txt, then for example I call cmake with `cmake -G"Visual Studio 10 Win64" -H".." -B"..\x64-opengl" -C"x64_CacheInit.txt" -DWITH_OPENGL=ON -DBUILD_MAPEDITOR=ON -DBUILD_ANIMVIEWER=ON`

Since there isn't really a standard layout for people's library paths I've been reluctant to post my files, but if you are doing a lot of building with different configurations that's the sort of method I recommend.

**Comment by Lego3** [comment]
I do roughly the same actually.

**Comment by TheCycoONE** [comment]
Seems to me this is the sort of thing that needs to be solved upstream at CMake.

**Comment by J-Shep** [comment]
>> Seems to me this is the sort of thing that needs to be solved upstream at CMake.

@TheCycoONE I will see what changes would need to be made and if they are changes which should be made upstream at CMAKE then I will send them a pull request.

**Comment by TheCycoONE** [comment]
@J-Shep You can see what I did with Visual Leak Detector in #636 but it only works if the files have normal locations.  I can't see how the vast majority of our libraries would be auto detected.

**Comment by TheCycoONE** [comment]
Use the `CorsixTH/deps` repo with `CMAKE_INCLUDE_PATH` and `CMAKE_LIB_PATH`
