### ISSUE TITLE
Patient go in to wrong room and crash (with video and save)

### ISSUE THREAD

**Issue by ledowong** [CorsixTH/CorsixTH#655]
video:
http://youtu.be/1XUWA-O3K2A

save: (use autosave1)
https://drive.google.com/file/d/0B05D0Cat5usfSjRtQV8yX2RiR1U/view?usp=sharing

**Comment by mugmuggy** [comment]
Just clearing this one out of the way. Was most likely due to
https://github.com/CorsixTH/CorsixTH/blob/fe1a526b5f1da2439b71d9641165bd2dcbf1bbc3/CorsixTH/Lua/humanoid_actions/die.lua#L293-L297
which has been changed since. The else not checking a valid empty tile, which probably put the patient through the door.
