### ISSUE TITLE
Possibility to use Moonscript

### ISSUE THREAD

**Issue by driverpt** [CorsixTH/CorsixTH#731]
As title says

**Comment by Alberth289346** [comment]
You don't expect us to know what it is eh? :)

http://moonscript.org/ it's a language built on top of lua, and can be compiled to lua 'on the fly'.

**Comment by driverpt** [comment]
Well yeah, sorry for that :-(, forgot to explain what moonscript was.

Well, I did some code snippets with moonscript and Lua, and trust me. The
code becomes much cleaner.

Moonscript is like Coffeescript (compiles to javascript).

**Comment by Alberth289346** [comment]
Can you explain why we would want to support Moonscript, and how you envision that in this project??  Suggesting something is one step, but without feasible plan, it's not going to fly.



I agree with you that Lua isn't ideal, but we have 90,000+ lines of it. Also, there are some non-standard Lua parts in the project, eg our own class definition, etc. How do you suggest to handle that?

I can see two possible directions for adding Moonscript.

a) Rewrite all to Moonscript.
Currently there are a number of Lua developers active, and 0 Moonscript developers. What you'd need is 2-3 very good Moonscript developers to rewrite the code base. Finding such people will take a year, and assuming you find such people, they need 2-3 years rewriting existing code. Besides the questionable assumptions (good Moonscript developers that are bored enough to switch to CorsixTH, and rewrite 'bad' Lua code to Moonscript code for 2 years?), there is little anyone else can do. Coding further in Lua is pointless, and it will be at least a year after finding a Moonscript developer, before some Moonscript-ish would work.
Effectively, the project won't move forward for at least 3 years in optimistic estimation. Most people call that 'dead project'.

The best chance for this to work, is to make a new project 'MoonTH' or so, and start from there. However, if you're going to rewrite from scratch (using existing Lua code as inspiration), I wouldn;t pick Moonscript, but eg Python.


b) Have some blend of Lua and Moonscript.
In order not to get completely out of hand, the existing Lua class things in the project must be compatible with whatever Moonscript uses and assumes. Without it, you won't be able to derive a new Window class from the existing Lua window base class, for example, or a Lua developer can't access some data from the Moonscript object.
I severely doubt that would work out of the box today. Demonstrating compatibility is the first step before even considering this blend idea.

Assuming the compatibility issues can be solved, you're facing a project with parts in C++, parts in Lua, and parts in Moonscript. As the recent exercise in upgrading to Lua 5.2 and 5.3 has proven, tracking upstream changes is a major pain in the behind, adding Moonscript won't help there.

How does a Lua developer operate in such a project? He can make some changes, but some of the things he needs don't work as he wants in Moonscript. He needs a Moonscript colleague to give him a hand. A Moonscript developer has the same problem, but the other way around.
You get a quite fragmented amount of code, where some parts become "don't touch it, it's another language". You already see this happening with C++, and C++ code is very very tiny, sitting at the edge of the project.
Many contributors in this project have troubles enough understanding one language. Adding a second language, with different syntax and ideas, doesn't really help, I think.



I don't see an easy way to migrate or merge Moonscript into the project. The directions I can see lead to a rewrite of everything (death of CorsixTH as we know it), or to some fragmented  multi-language code base, which is horrible to work in for many but some very good Lua/Moonscript developers.



While the process of migration itself looks quite non-feasible to me, at this moment (if you see other ways, please explain them), let's assume for a moment one could successfully merge Moonscript in some way. What would it bring us?

Basically Moonscript is a layer on top of Lua. It's strongly influenced by functional programming. It brings fancier syntax and language constructs (to the point of shooting itself in its own feet and introducing weird syntactic restrictions), and classes. While the details of classes are likely to differ between Moonscript and our implementation, they basically exist in the project, and are in use already.
The fancier/more-compact syntax is nice for local simplification of the code, but our main problem is large scale programming rather than small scale programming.
Moonscript doesn't seem to add much there that isn't already dealt with by moving data into objects.

In all, while Moonscript is a nicer language than Lua, I fear migration is going to be very painful at least, and the main benefits seem to be a little cleaner code at local scale, while dragging in yet another core third-party dependency.

Is there something I missed here? Am I totally wrong somewhere?

**Comment by driverpt** [comment]
Hello Alberth,

Thank you for explaining in detail how CorsixTH works.
The point of this issue, was more like a suggestion. I don't want to ruin
anyone's work. All i want is to have a Theme Hospital Remake, since it's a
game i liked a lot and contributed to it (See Grim Reaper feature).

You don't need to go aggressive on me, as i won't be feeding a flame war
with anybody.

I hope you understand that this was a mere suggestion to try to enchance
the product. i'm sorry if i ofended you in anyway, as it was not my
intention.

Os melhores cumprimentos,
Best Regards,
Met vriendelijke groet,

Luís Duarte

**Comment by SteveVaneeckhout** [comment]
It's not because he refutes your point with a good explanation that he's suddenly agressive.
See also: [Things You Should Never Do](http://www.joelonsoftware.com/articles/fog0000000069.html)

**Comment by Alberth289346** [comment]
Hi driverpt,

I wrote my post as a first analysis of what would happen if you tried to integrate Moonscript into the project. You have 90,000 lines Lua, a bunch of Lua and a few C++ developers, and you want to use or integrate Moonscript. How to do that?
(sort of a first exploration in that aera)

If your suggestion is going to fly, there has to be a clean road from 'now' to having Moonscript in the project. The question is thus, what roads to exist, and how clean are they?
A common way to find roads is to list a few, imagine what would happen if you take the road, and then see if you can wipe the obstacles away from the road (or get around them).

When I find a problem on the road, and I can't see an immediate way to get rid of it, I jump to my next tactic, which is analysis of the problem itself. Trying to solve a problem without understanding it is useless I think. It costs lots of effort, and you get nowhere. It's much more effective if you first work towards understanding why the problem is a problem, so you can look for an opening to attack it in its heart.

The first step in analyzing a problem is to identify what it is exactly what we are going to attack. That is, find agreement on that the problem really exists on the road, and if so what its shape is, and how it affects the road we want to go. For us to agree, we need to have a as clear as possible description. The best way (in my view) to do that is to call the ugly things by their ugly names. I believe it is essential to do, especially to hard problems like these.

So yeah, I was being aggressive. Not to you, but to the problems, trying to expose them as clearly as I can. After identification, one can move forward to talking about them, discussing, seeing if there are ways to make it work.
If you feel I am making unfair estimates or I am incomplete, please explain how my reasoning is wrong. I don't want a flamewar, I want to get an understanding of the problems we will encounter by exchanging views, trying to find out where we agree and where we don't agree (and why). If you can convince me by reasoning, I have no problems saying I was wrong.


I was not offended at all by your suggestion, in fact, I'd love to get rid of Lua. I think 90,000 lines Lua without typing information in any form is a nightmare.
However, no matter how much I want that, I must also have a road to the better alternative that everybody in the project is happy about. Having a closer look at the problems here will likely give useful insights into that, even if Moonscript turns out not to be the solution.
