### ISSUE TITLE
Resolution change error

### ISSUE THREAD

**Issue by TheMatia** [CorsixTH/CorsixTH#784]
Hey. I just tried playing version 5.0 for the first time (previously I've played 3.0) and the game froze (with the sound still playing) when I tried changing the resolution from the standard 800x600 to my pc's 1366x768 on the main menu.
 Error report:
![corsixth_error](https://cloud.githubusercontent.com/assets/13178182/8508490/beb81424-226a-11e5-967d-6b91b80b0b3a.png)

Every subsequent time I've tried to launch the game, it's failed and given this report:
![corsixth_error2](https://cloud.githubusercontent.com/assets/13178182/8508503/3532ffe2-226b-11e5-94ff-b223f3c97c20.png)

**Comment by Alberth289346** [comment]
the bad configuration got probably written to the configuration file, and it tries now to switch to that resolution every time you start the game, since by default it picks the resolution from the configuration file.
https://github.com/CorsixTH/CorsixTH/wiki/Configuration-File  explains where to find it
You can either edit the file with an ascii editor and fix the resolution (and perhaps the fullscreen setting?) or delete the file, and the game will make a new one, just like the first time you ran the program

**Comment by TheMatia** [comment]
Ok thanks. I deleted it and started again. It does this every time I try to use the 1366x768 resolution, but I've tried the next one down (1280x720) and that works fine. Don't know if my computer's just messing up or there's something I'm not seeing.

**Comment by Alberth289346** [comment]
CorsixTH/Lua/options.lua, line 87 says "{text = "1366x768 (16:9)",  width = 1366, height = 768}," so it seems the resolution is hard-coded. Perhaps something goes wrong in verifying your machine can actually handle the resolution that you select.

**Comment by alanwoolley** [comment]
Is this the same as #775, fixed in PR #776 ?

**Comment by TheCycoONE** [comment]
Yes
