### ISSUE TITLE
Can not play background music

### ISSUE THREAD

**Issue by caoli5288** [CorsixTH/CorsixTH#818]
First i see some error output like "/etc/timidity.cfg not found", so I install the timidity++ software and resove all error output.
But still not play background music.

**Comment by TheCycoONE** [comment]
You need timdity-freepats. Timidity itself cannot play music, follow the instructions for your operating system for installing timidity.

**Comment by TheCycoONE** [comment]
Duplicate of #746

**Comment by caoli5288** [comment]
Fedora's repos not contains this package.

**Comment by bobcanthelpyou** [comment]
```
yum install timidity-freepats
```
does not work?

**Comment by bobcanthelpyou** [comment]
Found the following info:

```
"The timidity-freepats package is obsolete.  Selecting this package for
installation will cause the soundfont-fluid-lite-patches package, which replaces this
one, to be installed instead."
```

Could you try that instead?

**Comment by caoli5288** [comment]
Also not exists. Fedora 22.

**Comment by bobcanthelpyou** [comment]
It is listed here: https://apps.fedoraproject.org/packages/fluid-soundfont-lite-patches/overview/

**Comment by bobcanthelpyou** [comment]
Maybe the package name is now:
```
yum install fluid-soundfont
```

**Comment by caoli5288** [comment]
Oh my god this is a 120MB+ package!

**Comment by caoli5288** [comment]
Why not pack a simple program that can handle MIDI?

**Comment by Alberth289346** [comment]
Because current sound cards cannot deal with MIDI any more, so the software needs to convert it to sounds for them

**Comment by caoli5288** [comment]
So how to resolve this problem? The fluid-soundfont package is too big(120MB) I do not want to try it. If install this package is a solution then it's also a stupid solution.

**Comment by TheCycoONE** [comment]
Timidity-freepats is just 33MB so look up instructions for how to get it for your distro, or provide your own mp3 directory in game settings instead of using the original midi.

There is no actual audio in a midi file, just instruments and notes. Old sound cards had the sounds built in but new ones don't. That's why you need these big sound fonts and there is no way around it except to use lower quality samples or not play the original tracks.

Please avoid calling us stupid. It's not motivating.

**Comment by caoli5288** [comment]
I see the in game message mp3 BGM dont support x64 platform yet? I get some error output like
```
Error in async music load callback: ./Lua/audio.lua:594: Could not load music file '/home/yiwan/Sounds/M01.mp3' (Unrecognized music format)
```
I see it load audio by SDL directly. So why not handle it by ffmpeg or other generic function?

**Comment by caoli5288** [comment]
:-)Sorry for my rude words.

**Comment by caoli5288** [comment]
Hey dear developers I found some interesting things.
Do you know OpenTTD? Yes this game play MIDI music also and when I try to install it by `yum install openttd` it depend the package fluid-soundfont(120MB).
But if I get the bin file from its website(about 11MB tarball file) It can play MIDI music directly! Not need install other package anymore.

**Comment by Alberth289346** [comment]
Yes I know OpenTTD, I rewrote the Gui sytem of it :p 

Like CorsixTH, also OpenTTD relies on external soundfonts to convert the MIDI to samples that the soundcard can play.

'yum' acknowledges this fact with the dependency. If you build from source, you can specify the sound font library (libtimidity). If you don't do that, you won't have music.

The only reason your 11MB file works is because you already installed soundfonts previously, eg with your 'yum' command to install the openttd version from the distribution.

As for MP3, there are some licensing problems with mp3, so many Linux distributions refrain from distributing that software (although often third-party repositories fill that gap). This is probably the reason why your mp3 cannot be played.

**Comment by caoli5288** [comment]
> The only reason your 11MB file works is because you already installed soundfonts previously, eg with your 'yum' command to install the openttd version from the distribution.

It's a great pleasure to talk to you. I like the game OpenTTD very much. But I'm sure I haven't done it. I can not install a more than 100M dependent library for a less than 15M game.

**Comment by TheCycoONE** [comment]
The warning about 64bit systems not supporting mp3 is obsolete (and should be fixed - let's open an issue about it.)  However it does depend on smpeg, which fedora does not include in their own repos because of their stance on mp3s (http://forums.fedoraforum.org/showthread.php?t=33457) but it is included in 3rd party repos for fedora. (rpm.pbone.net/index.php3?stat=3&search=smpeg)

Alternative sound track support has not received much attention; I believe it would also be trivial to support other formats supported by SDL_Mixer2 such as ogg vorbis which could play in fedora without third party repo libs (possibly as simple as changing this one line: https://github.com/CorsixTH/CorsixTH/blob/bc51ad3e391510c4b48517b06255996e11de5b0d/CorsixTH/Lua/audio.lua#L119)

ffmpeg and libav support are also possible (I wrote the ffmpeg and libav movie support for CorsixTH, so I've dealt with audio decoding with those libraries already), but it puts a lot of the maintenance burden that's currently covered by SDL_Mixer2 back on us, for a fairly small gain (smpeg is < 1mb, and we can save that space in ffmpeg by shipping a version compiled for only smacker video/audio support).

**Comment by TheCycoONE** [comment]
Note that smpeg 2.0.0 is the version needed.

**Comment by caoli5288** [comment]
I found the newest version is 0.4.5:-)

**Comment by caoli5288** [comment]
I found [http://wiki.libsdl.org/FAQDevelopment?highlight=%28mp3%29]()
and [http://www.icculus.org/SDL_sound/]()
The SDL_sound can handle MP3 audio file through libmpg123(a 200k lib).
Can you support this lib?(Sorry I can't found a pre-packaged smpeg 2.0.0 and does not want to convert my MP3 music to OGG to lose quality).

**Comment by TheCycoONE** [comment]
Unfortunately there is no SDL2 version of SDL_sound, the last release version of that library is from 2008, and the last commit was in 2012, so it may have been abandoned.

I think your path of least resistence if you don't want to compile packages yourself is going to be getting timidity-patch-freepats from another rpm distro e.g. http://rpm.pbone.net/index.php3/stat/4/idpl/27540465/dir/mageia_cauldron/com/timidity-patch-freepats-20060219-19.mga5.noarch.rpm.html

**Comment by caoli5288** [comment]
> I think your path of least resistence if you don't want to compile packages yourself is going to be getting timidity-patch-freepats from another rpm distro

I still not want a 33MB lib.

>  I believe it would also be trivial to support other formats supported by SDL_Mixer2 such as ogg vorbis which could play in fedora without third party repo libs (possibly as simple as changing this one line

I replace all "MP3" with "OGG" and put some ogg file on folder (convert by ffmpeg), get such error out put 
```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The callback handler.
A stack trace is included below, and the handler has been disconnected.
Error in async music load callback: ./Lua/audio.lua:594: Could not load music file '/home/yiwan/Softwares/CorsixTH/HOSP/MUSIC/Theme Hospital - Steady (ZR Remix).ogg' (Unrecognized music format)
stack traceback:
	[C]: in function 'yield'
	./Lua/app.lua:753: in function <./Lua/app.lua:748>
```

**Comment by TheCycoONE** [comment]
I said that it would require a change in CorsixTH and pointed out the line (https://github.com/CorsixTH/CorsixTH/issues/818#issuecomment-123704315)

**Comment by caoli5288** [comment]
> I said that it would require a change in CorsixTH and pointed out the line (#818 (comment))

I done it.

**Comment by TheCycoONE** [comment]
Ah I see.  Make sure you have libvorbis installed, because that's what SDL_Mixer 2 uses to open it. Beyond that, you're getting outside of stuff I've tried so I won't be able to help at this time.

**Comment by caoli5288** [comment]
I sure libvorbis installed and it not be supported. Maybe you can test and add support to some free audio format.

**Comment by caoli5288** [comment]
![2015-07-23 12-25-06](https://cloud.githubusercontent.com/assets/3120587/8843070/df5bfcb6-3135-11e5-97a1-26be45006e94.png)

**Comment by caoli5288** [comment]
Pre-build package have no libvorbis support?
