### ISSUE TITLE
Psychiatrist Chair can overlap bookcase

### ISSUE THREAD

**Issue by therealgreenpower** [CorsixTH/CorsixTH#89]
When playing CorsixTH trunk with demo files, there's a rendering bug in which if a psychiatrist sits in an armchair, and it's located behind another object, that armchair is rendered over all near objects.

**Comment by MandrakeHorse** [comment]
To reproduce this issue, the comfy chair needs to be orientated so that the psychiatrist faces south-east when sitting down. It does not occur when the chair is rotated so that he faces south-west.

Save file - [issue89_CorsixTHsave.zip](https://github.com/CorsixTH/CorsixTH/files/12708604/issue89_CorsixTHsave.zip)

**Comment by MandrakeHorse** [comment]
There's a variation of this glitch that occurs when the comfy chair is placed south-west of the bookcase: when the Doctor consults a book, the bookcase will overlap the chair.
![2023-10-06 23_34_19-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/f78ee2b4-8d62-48ff-bf1a-09fb35ba9692)

**Comment by Alberth289346** [comment]
Reporting more of these glitches isn't really needed. We know they exist in half a zillion variations, and more if you start looking for them,  
Cyco looked at the problem already and established that the current way of painting rooms to the screen is simply broken beyond repair. The current solution is never going to fix all render bugs.

As such, it's not going to be a small local fix with a testcase like you made to verify it's indeed fixed. Instead, the entire paint code must be taken out and replaced by something better. Trouble is, we don't yet know what that "something" should be. I think we also established that likely the current paint code doesn't get enough information to solve the problem, so that needs some thinking too.

This is basically the point where we are currently wrt this problem. No easy solution available, I am afraid.

**Comment by lewri** [comment]
> Reporting more of these glitches isn't really needed. We know they exist in half a zillion variations, and more if you start looking for them, Cyco looked at the problem already and established that the current way of painting rooms to the screen is simply broken beyond repair. The current solution is never going to fix all render bugs.
> 
> As such, it's not going to be a small local fix with a testcase like you made to verify it's indeed fixed. Instead, the entire paint code must be taken out and replaced by something better. Trouble is, we don't yet know what that "something" should be. I think we also established that likely the current paint code doesn't get enough information to solve the problem, so that needs some thinking too.
> 
> This is basically the point where we are currently wrt this problem. No easy solution available, I am afraid.

This reply really belongs in the meta if that is of the current mindset (or at least a summary of the relevant parts).

**Comment by Alberth289346** [comment]
Good point, done

**Comment by lewri** [comment]
Merged into meta
