### ISSUE TITLE
On ArchLinux, no background music

### ISSUE THREAD

**Issue by NerosTie** [CorsixTH/CorsixTH#941]
Data files from Origin and no issue on Windows.

On ArchLinux (https://aur.archlinux.org/packages/corsix-th), there is no background music.
Maybe this error is related: 
`Cannot check for updates since LuaSocket is not available.`

I can't say much...

**Comment by TheCycoONE** [comment]
The message you pasted is just a warning about not being able to check for updates because luasocket isn't installed. It isn't related to background music.

The most likely reason you're not hearing background audio is that you don't have Timidity set up correctly: https://wiki.archlinux.org/index.php/Timidity

Otherwise, check your music settings in the config.txt file

**Comment by NerosTie** [comment]
https://wiki.archlinux.org/index.php/Timidity#Freepats

I didn't know I had to do this but it was easy. Again, thank you!
